// Generated by Framer (a4aa1f7)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ZelIt30ALO921MYxWHXw/it5UzZWiNTEtsJnoElbb/pU1l54HaN.js";
import Chevron from "https://framerusercontent.com/modules/sN9iqB5T621O7plHDw6W/zicA6u611Rrpt3hJjLBY/RaCuvmvck.js";
const ChevronFonts = getFonts(Chevron);
const enabledGestures = { IT_tG5lTF: { hover: true } };
const cycleOrder = [
  "IT_tG5lTF",
  "qd4UgaKG3",
  "GPf4dlmU0",
  "NvKg25vf5",
  "z0VbAoCS1",
];
const serializationHash = "framer-hJZLp";
const variantClassNames = {
  GPf4dlmU0: "framer-v-1d5566j",
  IT_tG5lTF: "framer-v-336bbo",
  NvKg25vf5: "framer-v-1wu53iw",
  qd4UgaKG3: "framer-v-1poozmd",
  z0VbAoCS1: "framer-v-ptoir5",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.2,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Default: "IT_tG5lTF",
  Disabled: "GPf4dlmU0",
  Error: "z0VbAoCS1",
  Loading: "qd4UgaKG3",
  Success: "NvKg25vf5",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "IT_tG5lTF",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "IT_tG5lTF",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["qd4UgaKG3", "NvKg25vf5", "z0VbAoCS1"].includes(baseVariant))
      return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.button, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-336bbo",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          "data-reset": "button",
          layoutDependency: layoutDependency,
          layoutId: "IT_tG5lTF",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-29b0dbc5-7e1f-4b3e-8954-a3e1672ca3b5, rgb(198, 241, 157))",
            borderBottomLeftRadius: 8,
            borderBottomRightRadius: 8,
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            opacity: 1,
            ...style,
          },
          variants: {
            "IT_tG5lTF-hover": {
              backgroundColor:
                "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
              opacity: 1,
            },
            GPf4dlmU0: { opacity: 0.5 },
            NvKg25vf5: { opacity: 1 },
            z0VbAoCS1: { backgroundColor: "rgb(255, 179, 171)", opacity: 1 },
          },
          ...addPropertyOverrides(
            {
              "IT_tG5lTF-hover": { "data-framer-name": undefined },
              GPf4dlmU0: { "data-framer-name": "Disabled" },
              NvKg25vf5: { "data-framer-name": "Success" },
              qd4UgaKG3: { "data-framer-name": "Loading" },
              z0VbAoCS1: { "data-framer-name": "Error" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-183mk7o",
                  "data-styles-preset": "pU1l54HaN",
                  children: "Submit",
                }),
              }),
              className: "framer-1njlpmq",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "XjlbftiFR",
              style: {
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              variants: {
                "IT_tG5lTF-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255))",
                },
                z0VbAoCS1: { "--extracted-r6o4lv": "rgb(94, 0, 0)" },
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  "IT_tG5lTF-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-183mk7o",
                        "data-styles-preset": "pU1l54HaN",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)))",
                        },
                        children: "Submit",
                      }),
                    }),
                  },
                  NvKg25vf5: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-183mk7o",
                        "data-styles-preset": "pU1l54HaN",
                        children: "thank you!",
                      }),
                    }),
                  },
                  qd4UgaKG3: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-183mk7o",
                        "data-styles-preset": "pU1l54HaN",
                        children: "Submitting…",
                      }),
                    }),
                  },
                  z0VbAoCS1: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-183mk7o",
                        "data-styles-preset": "pU1l54HaN",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(94, 0, 0))",
                        },
                        children: "error",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 20,
                width: "20px",
                y:
                  (componentViewport?.y || 0) +
                  (0 + ((componentViewport?.height || 58) - 0 - 20) / 2),
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-103z84i-container",
                  layoutDependency: layoutDependency,
                  layoutId: "rS7iXCDcu-container",
                  nodeId: "rS7iXCDcu",
                  rendersWithMotion: true,
                  scopeId: "yE2QfUzJH",
                  children: /*#__PURE__*/ _jsx(Chevron, {
                    height: "100%",
                    id: "rS7iXCDcu",
                    layoutId: "rS7iXCDcu",
                    style: { height: "100%", width: "100%" },
                    variant: "UUR_EIbHV",
                    width: "100%",
                    ...addPropertyOverrides(
                      { "IT_tG5lTF-hover": { variant: "Yn0QgI7Ea" } },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-hJZLp.framer-15siux6, .framer-hJZLp .framer-15siux6 { display: block; }",
  ".framer-hJZLp.framer-336bbo { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: 58px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 130px; }",
  ".framer-hJZLp .framer-1njlpmq { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-hJZLp .framer-103z84i-container { flex: none; height: 20px; position: relative; width: 20px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 58
 * @framerIntrinsicWidth 130
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"qd4UgaKG3":{"layout":["fixed","fixed"]},"GPf4dlmU0":{"layout":["fixed","fixed"]},"NvKg25vf5":{"layout":["fixed","fixed"]},"z0VbAoCS1":{"layout":["fixed","fixed"]},"fTC3SChkA":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameryE2QfUzJH = withCSS(Component, css, "framer-hJZLp");
export default FrameryE2QfUzJH;
FrameryE2QfUzJH.displayName = "Button";
FrameryE2QfUzJH.defaultProps = { height: 58, width: 130 };
addPropertyControls(FrameryE2QfUzJH, {
  variant: {
    options: ["IT_tG5lTF", "qd4UgaKG3", "GPf4dlmU0", "NvKg25vf5", "z0VbAoCS1"],
    optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FrameryE2QfUzJH,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ChevronFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameryE2QfUzJH",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "58",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"qd4UgaKG3":{"layout":["fixed","fixed"]},"GPf4dlmU0":{"layout":["fixed","fixed"]},"NvKg25vf5":{"layout":["fixed","fixed"]},"z0VbAoCS1":{"layout":["fixed","fixed"]},"fTC3SChkA":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "130",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
