// Generated by Framer (6e662ac)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/nu7ybpUpTlLbhjJUHl5K/tjaztxXynZDamW7r4dU0/pRcg_9vKm.js";
import Arrow from "https://framerusercontent.com/modules/mGw1ko1s24RUtSz5T9Eb/XAOyPQTKk6jJJTgHIIVb/iGM5o1ti5.js";
const ArrowFonts = getFonts(Arrow);
const enabledGestures = {
  fCTiJpW6H: { hover: true },
  I8eGm8lDi: { hover: true },
};
const cycleOrder = ["I8eGm8lDi", "fCTiJpW6H", "qnabLRyPS"];
const serializationHash = "framer-mrhbg";
const variantClassNames = {
  fCTiJpW6H: "framer-v-1qe0yjd",
  I8eGm8lDi: "framer-v-1hjxauo",
  qnabLRyPS: "framer-v-y6zz1c",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.5,
  ease: [0.73, 0, 0.32, 1],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "I8eGm8lDi",
  "Variant 2": "fCTiJpW6H",
  mobile: "qnabLRyPS",
};
const getProps = ({
  badge,
  height,
  id,
  image,
  link,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    FzGwBzq9k:
      title ??
      props.FzGwBzq9k ??
      "Carbon Markets Built on Truth, Not Estimates",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "I8eGm8lDi",
    xURZtFZOP: badge ?? props.xURZtFZOP ?? "[Nature-Based Solutions]",
    XZLIyH3lX: image ??
      props.XZLIyH3lX ?? {
        alt: "",
        pixelHeight: 2796,
        pixelWidth: 2744,
        src: "https://framerusercontent.com/images/fje9aeALhKA2pJC5NpbCtOyibA.png?scale-down-to=1024",
        srcSet:
          "https://framerusercontent.com/images/fje9aeALhKA2pJC5NpbCtOyibA.png?scale-down-to=1024 1004w,https://framerusercontent.com/images/fje9aeALhKA2pJC5NpbCtOyibA.png?scale-down-to=2048 2009w,https://framerusercontent.com/images/fje9aeALhKA2pJC5NpbCtOyibA.png 2744w",
      },
    YidS_wKhi: link ?? props.YidS_wKhi,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    XZLIyH3lX,
    FzGwBzq9k,
    xURZtFZOP,
    YidS_wKhi,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "I8eGm8lDi",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const OhBpNEoxY768rko = activeVariantCallback(async (...args) => {
    setVariant("I8eGm8lDi");
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "qnabLRyPS") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: YidS_wKhi,
          motionChild: true,
          nodeId: "I8eGm8lDi",
          openInNewTab: false,
          scopeId: "YJbdpO0IN",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1hjxauo",
              className,
              classNames
            )} framer-b2aqlg`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "I8eGm8lDi",
            ref: refBinding,
            style: {
              borderBottomLeftRadius: 24,
              borderBottomRightRadius: 24,
              borderTopLeftRadius: 24,
              borderTopRightRadius: 24,
              ...style,
            },
            variants: {
              "fCTiJpW6H-hover": {
                borderBottomLeftRadius: 22,
                borderBottomRightRadius: 22,
                borderTopLeftRadius: 22,
                borderTopRightRadius: 22,
              },
              "I8eGm8lDi-hover": {
                borderBottomLeftRadius: 22,
                borderBottomRightRadius: 22,
                borderTopLeftRadius: 22,
                borderTopRightRadius: 22,
              },
            },
            ...addPropertyOverrides(
              {
                "fCTiJpW6H-hover": { "data-framer-name": undefined },
                "I8eGm8lDi-hover": { "data-framer-name": undefined },
                fCTiJpW6H: { "data-framer-name": "Variant 2" },
                qnabLRyPS: { "data-framer-name": "mobile" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1uwj0rf",
                  layoutDependency: layoutDependency,
                  layoutId: "fjvzjqs35",
                  style: {
                    backgroundColor: "rgb(199, 241, 157)",
                    borderBottomLeftRadius: 999,
                    borderBottomRightRadius: 999,
                    borderTopLeftRadius: 999,
                    borderTopRightRadius: 999,
                  },
                }),
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 0
                  ),
                  sizes: componentViewport?.width || "100vw",
                  ...toResponsiveImage(XZLIyH3lX),
                },
                className: "framer-12glm9p",
                "data-framer-name": "Rectangle 3619",
                layoutDependency: layoutDependency,
                layoutId: "I9:509;9:464",
                style: {
                  borderBottomLeftRadius: 24,
                  borderBottomRightRadius: 24,
                  borderTopLeftRadius: 24,
                  borderTopRightRadius: 24,
                },
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1c4fayp",
                "data-framer-name": "Top",
                layoutDependency: layoutDependency,
                layoutId: "k046mL7g4",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QgTW9uby01MDA=",
                          "--framer-font-family": '"Geist Mono", monospace',
                          "--framer-font-size": "14px",
                          "--framer-font-weight": "500",
                          "--framer-line-height": "90%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "[Nature-Based Solutions]",
                      }),
                    }),
                    className: "framer-1713mdg",
                    "data-framer-name": "[Nature-Based Solutions]",
                    fonts: ["GF;Geist Mono-500"],
                    layoutDependency: layoutDependency,
                    layoutId: "I9:509;9:469",
                    style: {
                      "--extracted-r6o4lv": "rgb(255, 255, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: xURZtFZOP,
                    variants: {
                      "fCTiJpW6H-hover": {
                        "--extracted-r6o4lv":
                          "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                      },
                      "I8eGm8lDi-hover": {
                        "--extracted-r6o4lv":
                          "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                      },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        "fCTiJpW6H-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "R0Y7R2Vpc3QgTW9uby01MDA=",
                                "--framer-font-family":
                                  '"Geist Mono", monospace',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "500",
                                "--framer-line-height": "90%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "[Nature-Based Solutions]",
                            }),
                          }),
                        },
                        "I8eGm8lDi-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "R0Y7R2Vpc3QgTW9uby01MDA=",
                                "--framer-font-family":
                                  '"Geist Mono", monospace',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "500",
                                "--framer-line-height": "90%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "[Nature-Based Solutions]",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 38,
                    y:
                      (componentViewport?.y || 0) +
                      40 +
                      (0 +
                        0 +
                        (((componentViewport?.height || 699) - 80 - 114) / 1) *
                          0) +
                      0,
                    ...addPropertyOverrides(
                      {
                        qnabLRyPS: {
                          y:
                            (componentViewport?.y || 0) +
                            16 +
                            (0 +
                              0 +
                              (((componentViewport?.height || 390) - 32 - 114) /
                                1) *
                                0) +
                            0,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-xsjzi8-container",
                        layoutDependency: layoutDependency,
                        layoutId: "FQjxf5hrD-container",
                        nodeId: "FQjxf5hrD",
                        rendersWithMotion: true,
                        scopeId: "YJbdpO0IN",
                        children: /*#__PURE__*/ _jsx(Arrow, {
                          height: "100%",
                          id: "FQjxf5hrD",
                          layoutId: "FQjxf5hrD",
                          OhBpNEoxY: OhBpNEoxY768rko,
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1mio82u",
                "data-framer-name": "Bottom",
                layoutDependency: layoutDependency,
                layoutId: "d5cvKsITA",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h4, {
                      className: "framer-styles-preset-13kgpfl",
                      "data-styles-preset": "pRcg_9vKm",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-1eung3n, var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)))",
                      },
                      children: "Carbon Markets Built on Truth, Not Estimates",
                    }),
                  }),
                  className: "framer-19w5vzv",
                  "data-framer-name":
                    "Carbon Markets Built on Truth, Not Estimates",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "I9:509;9:468",
                  style: {
                    "--extracted-1eung3n":
                      "var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: FzGwBzq9k,
                  variants: {
                    "fCTiJpW6H-hover": {
                      "--extracted-1eung3n":
                        "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                    },
                    "I8eGm8lDi-hover": {
                      "--extracted-1eung3n":
                        "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                    },
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      "fCTiJpW6H-hover": {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h4, {
                            className: "framer-styles-preset-13kgpfl",
                            "data-styles-preset": "pRcg_9vKm",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-1eung3n, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)))",
                            },
                            children:
                              "Carbon Markets Built on Truth, Not Estimates",
                          }),
                        }),
                      },
                      "I8eGm8lDi-hover": {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h4, {
                            className: "framer-styles-preset-13kgpfl",
                            "data-styles-preset": "pRcg_9vKm",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-1eung3n, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)))",
                            },
                            children:
                              "Carbon Markets Built on Truth, Not Estimates",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-mrhbg.framer-b2aqlg, .framer-mrhbg .framer-b2aqlg { display: block; }",
  ".framer-mrhbg.framer-1hjxauo { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; height: 699px; justify-content: space-between; overflow: hidden; padding: 40px 28px 40px 28px; position: relative; text-decoration: none; width: 682px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-mrhbg .framer-1uwj0rf { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 37px); overflow: visible; position: absolute; right: 28px; top: 40px; width: 37px; z-index: 1; }",
  ".framer-mrhbg .framer-12glm9p { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 0; }",
  ".framer-mrhbg .framer-1c4fayp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
  ".framer-mrhbg .framer-1713mdg { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-mrhbg .framer-xsjzi8-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-mrhbg .framer-1mio82u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
  ".framer-mrhbg .framer-19w5vzv { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 87%; word-break: break-word; word-wrap: break-word; }",
  ".framer-mrhbg.framer-v-1qe0yjd .framer-19w5vzv { flex: 1 0 0px; width: 1px; }",
  ".framer-mrhbg.framer-v-y6zz1c.framer-1hjxauo { cursor: unset; height: 390px; padding: 16px; width: 390px; }",
  ".framer-mrhbg.framer-v-1hjxauo.hover .framer-1uwj0rf { aspect-ratio: unset; height: 395%; left: calc(93.108504398827% - 395% / 2); right: unset; top: calc(8.297567954220337% - 395% / 2); width: 395%; }",
  ".framer-mrhbg.framer-v-1qe0yjd.hover .framer-1uwj0rf { aspect-ratio: unset; height: 323%; left: calc(93.108504398827% - 319.4888178913738% / 2); right: unset; top: calc(8.297567954220337% - 323.1017770597738% / 2); width: 319%; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 699
 * @framerIntrinsicWidth 682
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"fCTiJpW6H":{"layout":["fixed","fixed"]},"qnabLRyPS":{"layout":["fixed","fixed"]},"VDGseoj40":{"layout":["fixed","fixed"]},"Wz23WTKV2":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"XZLIyH3lX":"image","FzGwBzq9k":"title","xURZtFZOP":"badge","YidS_wKhi":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerYJbdpO0IN = withCSS(Component, css, "framer-mrhbg");
export default FramerYJbdpO0IN;
FramerYJbdpO0IN.displayName = "Card Solutions";
FramerYJbdpO0IN.defaultProps = { height: 699, width: 682 };
addPropertyControls(FramerYJbdpO0IN, {
  variant: {
    options: ["I8eGm8lDi", "fCTiJpW6H", "qnabLRyPS"],
    optionTitles: ["Variant 1", "Variant 2", "mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  XZLIyH3lX: {
    __defaultAssetReference:
      "data:framer/asset-reference,fje9aeALhKA2pJC5NpbCtOyibA.png?originalFilename=Rectangle+3619.png&preferredSize=auto",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,fje9aeALhKA2pJC5NpbCtOyibA.png?originalFilename=Rectangle+3619.png&preferredSize=auto",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  FzGwBzq9k: {
    defaultValue: "Carbon Markets Built on Truth, Not Estimates",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  xURZtFZOP: {
    defaultValue: "[Nature-Based Solutions]",
    displayTextArea: false,
    title: "Badge",
    type: ControlType.String,
  },
  YidS_wKhi: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerYJbdpO0IN,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist Mono",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ArrowFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerYJbdpO0IN",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"fCTiJpW6H":{"layout":["fixed","fixed"]},"qnabLRyPS":{"layout":["fixed","fixed"]},"VDGseoj40":{"layout":["fixed","fixed"]},"Wz23WTKV2":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "682",
        framerIntrinsicHeight: "699",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"XZLIyH3lX":"image","FzGwBzq9k":"title","xURZtFZOP":"badge","YidS_wKhi":"link"}',
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
