// Generated by Framer (9e0d514)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "1wtdf6h", mediaQuery: "(min-width: 2560px)" },
      {
        hash: "1lqjm5p",
        mediaQuery: "(min-width: 1920px) and (max-width: 2559.98px)",
      },
      {
        hash: "118f0c",
        mediaQuery: "(min-width: 1440px) and (max-width: 1919.98px)",
      },
      {
        hash: "1m40t0f",
        mediaQuery: "(min-width: 960px) and (max-width: 1439.98px)",
      },
      { hash: "zp0d8j", mediaQuery: "(max-width: 959.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {
      AJ8NKVcRT: "alien",
      FIftrkqf9: "trg-why-1",
      FtNhAyTuY: "trg-why-2",
      gSSZsDe8A: "steps-trg",
      jvSL5TNtT: "trg-steps-1",
      k4n_s2AG2: "nav-swap",
      kclVukbJZ: "img-scale",
      o1lPWah4D: "polygon-trusted-by",
      O2m5hGwHX: "poly-1-2",
      PNgXIFyv8: "poly-3",
      QmqgAHNoG: "timeline-suelta",
      RaTYr8f8B: "poly-1-1",
      sAnnBpR2l: "poly-4",
      ufzxLRt4j: "trg-steps-2",
      UNa8OEz_o: "trg-timeline",
      VAP4JFL_R: "poly-1-3",
      vnVTgj4nT: "poly-1",
      yukJScuX8: "trg-steps-3",
      Zql_JUlDl: "poly-2",
    },
    framerSearch: { index: true },
    robots: "max-image-preview:large",
    serializationId: "framer-3jEjW",
    socialImage:
      "https://framerusercontent.com/assets/iqDsJXUinpINeX8HP9OQ8cuObRE.png",
    title: "Blockchain",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
