// Generated by Framer (f36d8c8)
import {
  addPropertyControls as e,
  ControlType as l,
  QueryEngine as t,
} from "framer";
import {
  DatabaseCollection as a,
  DatabaseDictionaryIndex as r,
} from "./B33wnMHvT-0.js";
import { getRichTextJsonResolver as m } from "./B33wnMHvT-1.js";
let i = {
    bqPqvPNdP: { isNullable: !0, type: l.ResponsiveImage },
    btX_caC5q: { isNullable: !0, type: l.ResponsiveImage },
    BYb9x2u2D: { isNullable: !0, type: l.String },
    createdAt: { isNullable: !0, type: l.Date },
    DxIPVsLGG: { isNullable: !0, type: l.String },
    ewJaI1vsI: { isNullable: !0, type: l.String },
    iCjyzjRf1: { isNullable: !0, type: l.ResponsiveImage },
    id: { isNullable: !1, type: l.String },
    jEbWympg2: { isNullable: !0, type: l.Date },
    kMlaX7Ocf: { isNullable: !0, type: l.RichText },
    MATjgCnVq: { isNullable: !0, type: l.Number },
    MV8mHGdUQ: { isNullable: !0, type: l.String },
    nextItemId: { isNullable: !0, type: l.String },
    Oyn_CQ8yA: { isNullable: !0, type: l.RichText },
    previousItemId: { isNullable: !0, type: l.String },
    qUp8fFSQv: { isNullable: !0, type: l.Boolean },
    SzMq7L17D: { isNullable: !0, type: l.String },
    u8zx7p91P: { isNullable: !0, type: l.ResponsiveImage },
    updatedAt: { isNullable: !0, type: l.Date },
    UX6K9ZGvs: { isNullable: !0, type: l.RichText },
    w0jAsOFWp: { isNullable: !0, type: l.String },
    yvKxVbhVQ: { isNullable: !0, type: l.RichText },
    z15_lmRRt: { isNullable: !0, type: l.Enum },
    zDt8N9Xms: { isNullable: !0, type: l.ResponsiveImage },
    zrRRuZCZI: { isNullable: !0, type: l.RichText },
  },
  o = ["id"],
  n = { type: 1 },
  c = ["previousItemId"],
  s = ["nextItemId"],
  u = ["id", "SzMq7L17D"],
  d = ["SzMq7L17D", "id"],
  p = ["BYb9x2u2D"],
  f = { type: 0 },
  y = ["DxIPVsLGG"],
  w = ["ewJaI1vsI"],
  h = ["SzMq7L17D"],
  g = ["jEbWympg2"],
  R = ["qUp8fFSQv"],
  v = ["z15_lmRRt"],
  N = ["zDt8N9Xms"],
  S = ["MV8mHGdUQ"],
  x = ["w0jAsOFWp"],
  M = ["MATjgCnVq"],
  b = ["zrRRuZCZI"],
  T = ["iCjyzjRf1"],
  I = ["Oyn_CQ8yA"],
  B = ["u8zx7p91P"],
  L = ["bqPqvPNdP"],
  U = ["yvKxVbhVQ"],
  H = ["btX_caC5q"],
  V = ["UX6K9ZGvs"],
  D = ["kMlaX7Ocf"],
  z = [],
  C = (e) => {
    let l = z[e];
    if (l) return l().then((e) => e.default);
  },
  q = {},
  j = m(q),
  G = new t(),
  P = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./B33wnMHvT-chunk-default-0.framercms",
            "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "1567dbd9-84cd-4dd7-a5b6-a7d3b93e568cdefault",
        indexes: [
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: o,
            range: { from: 0, to: 73 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: c,
            range: { from: 73, to: 145 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: s,
            range: { from: 145, to: 213 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: u,
            range: { from: 213, to: 403 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: d,
            range: { from: 403, to: 593 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: p,
            range: { from: 593, to: 779 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: y,
            range: { from: 779, to: 1027 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: w,
            range: { from: 1027, to: 1133 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: h,
            range: { from: 1133, to: 1289 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: g,
            range: { from: 1289, to: 1359 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: R,
            range: { from: 1359, to: 1415 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: v,
            range: { from: 1415, to: 1495 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: N,
            range: { from: 1495, to: 2343 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: S,
            range: { from: 2343, to: 2437 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: x,
            range: { from: 2437, to: 2514 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: M,
            range: { from: 2514, to: 2584 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: b,
            range: { from: 2584, to: 4639 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: T,
            range: { from: 4639, to: 5443 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: I,
            range: { from: 5443, to: 7879 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: B,
            range: { from: 7879, to: 8205 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: L,
            range: { from: 8205, to: 8533 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: U,
            range: { from: 8533, to: 9963 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: H,
            range: { from: 9963, to: 10725 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: V,
            range: { from: 10725, to: 11599 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: f,
            collectionSchema: i,
            fieldNames: D,
            range: { from: 11599, to: 12013 },
            url: new URL(
              "./B33wnMHvT-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/s1WjcTp5of1oFg6IotGU/owr39drwpBsU6BPW8ucU/B33wnMHvT.js"
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: j,
        resolveVectorSetItem: C,
        schema: i,
      }),
    },
    displayName: "Case Studies",
    id: "1567dbd9-84cd-4dd7-a5b6-a7d3b93e568c",
  };
export default P;
e(P, {
  BYb9x2u2D: { defaultValue: "", title: "Title", type: l.String },
  DxIPVsLGG: {
    defaultValue: "Preview placeholder Case Studies",
    maxLength: 127,
    title: "Preview",
    type: l.String,
  },
  ewJaI1vsI: {
    defaultValue: "Case Studies - Prakriti",
    title: "Description",
    type: l.String,
  },
  SzMq7L17D: { preventLocalization: !0, title: "Slug", type: l.String },
  jEbWympg2: { defaultValue: "", title: "Date", type: l.Date },
  qUp8fFSQv: { defaultValue: !1, title: "Highlight", type: l.Boolean },
  z15_lmRRt: {
    defaultValue: "S8FjHUG40",
    options: ["S8FjHUG40", "b6cNdtK0U"],
    optionTitles: ["Nature-Based", "Supply Chain"],
    title: "Category",
    type: l.Enum,
  },
  zDt8N9Xms: { title: "IMG Main", type: l.ResponsiveImage },
  MV8mHGdUQ: { defaultValue: "", title: "Author", type: l.String },
  w0jAsOFWp: { defaultValue: "", title: "Autor's Role", type: l.String },
  MATjgCnVq: { defaultValue: 0, title: "Reading Time", type: l.Number },
  zrRRuZCZI: { defaultValue: "", title: "paragraph 1", type: l.RichText },
  iCjyzjRf1: { title: "IMG_Body 1", type: l.ResponsiveImage },
  Oyn_CQ8yA: { defaultValue: "", title: "paragraph 2", type: l.RichText },
  u8zx7p91P: { title: "IMG_Body 2 A", type: l.ResponsiveImage },
  bqPqvPNdP: { title: "IMG_Body 2 B", type: l.ResponsiveImage },
  yvKxVbhVQ: { defaultValue: "", title: "paragraph 3", type: l.RichText },
  btX_caC5q: { title: "IMG_Body 3", type: l.ResponsiveImage },
  UX6K9ZGvs: { defaultValue: "", title: "paragraph 4", type: l.RichText },
  kMlaX7Ocf: { defaultValue: "", title: "Mono Paragraph", type: l.RichText },
  createdAt: { title: "Created", type: l.Date },
  updatedAt: { title: "Updated", type: l.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/B33wnMHvT:default",
    title: "Previous",
    type: l.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/B33wnMHvT:default",
    title: "Next",
    type: l.CollectionReference,
  },
});
export const z15_lmRRtToDisplayName = (e, l) => {
  switch ((l?.fallback, e)) {
    case "S8FjHUG40":
      return "Nature-Based";
    case "b6cNdtK0U":
      return "Supply Chain";
    default:
      return "";
  }
};
export const enumToDisplayNameFunctions = { z15_lmRRt: z15_lmRRtToDisplayName };
export const utils = {
  async getSlugByRecordId(e, l) {
    let [t] = await G.query(
      {
        from: { data: P, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "SzMq7L17D", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.SzMq7L17D;
  },
  async getRecordIdBySlug(e, l) {
    let [t] = await G.query(
      {
        from: { data: P, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "SzMq7L17D", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerCollectionUtils: "1",
        framerColorSyntax: "false",
        framerAutoSizeImages: "true",
        framerEnumToDisplayNameUtils: "2",
        framerCollectionId: "B33wnMHvT",
        framerRecordIdKey: "id",
        framerSlug: "SzMq7L17D",
        framerContractVersion: "1",
        framerData: "true",
      },
    },
    z15_lmRRtToDisplayName: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
