// Generated by Framer (df7882f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import SocialMediaShareButtons from "https://framerusercontent.com/modules/6otkueI5eHWLj0vNTfxn/QvgSj9XG9loHrMRLIk1e/SocialMediaShareButtons.js";
import Redes_Blog_Article from "https://framerusercontent.com/modules/CfgaiQ1hmzdtuyOewhyV/0jqP5Lj86lv0PkYbvGvT/M14Bgx6O9.js";
const Redes_Blog_ArticleFonts = getFonts(Redes_Blog_Article);
const SocialMediaShareButtonsFonts = getFonts(SocialMediaShareButtons);
const enabledGestures = { qb_IVLxRv: { hover: true } };
const serializationHash = "framer-tZAHB";
const variantClassNames = { qb_IVLxRv: "framer-v-ys531d" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "qb_IVLxRv",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-ys531d",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "qb_IVLxRv",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { "qb_IVLxRv-hover": { "data-framer-name": undefined } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 20,
              width: "77px",
              y:
                (componentViewport?.y || 0) +
                (0 + ((componentViewport?.height || 20) - 0 - 20) / 2),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-13yahkw-container",
                "data-framer-name": "linkedin",
                layoutDependency: layoutDependency,
                layoutId: "OJkkgAScp-container",
                name: "linkedin",
                nodeId: "OJkkgAScp",
                rendersWithMotion: true,
                scopeId: "QhLe9Cy4m",
                children: /*#__PURE__*/ _jsx(Redes_Blog_Article, {
                  height: "100%",
                  id: "OJkkgAScp",
                  layoutId: "OJkkgAScp",
                  name: "linkedin",
                  s_2H0AclU: "linkedin",
                  style: { height: "100%", width: "100%" },
                  variant: "m_y1rrmre",
                  width: "100%",
                  ...addPropertyOverrides(
                    { "qb_IVLxRv-hover": { variant: "KDLJo2sA0" } },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1jcirej-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "zs0FmcCqY-container",
                nodeId: "zs0FmcCqY",
                rendersWithMotion: true,
                scopeId: "QhLe9Cy4m",
                style: { opacity: 0 },
                transformTemplate: transformTemplate1,
                children: /*#__PURE__*/ _jsx(SocialMediaShareButtons, {
                  borderRadius: 0,
                  colorType: "brand",
                  enablePlatforms: "linkedin",
                  enableUrlShorten: false,
                  headingColor: "rgb(0, 0, 0)",
                  headingFontFamily: "Inter",
                  height: "100%",
                  iconsBackground: "rgb(0, 0, 0)",
                  iconsColor: "rgb(255, 255, 255)",
                  iconsPadding: 20,
                  iconsSize: 145,
                  id: "zs0FmcCqY",
                  layoutId: "zs0FmcCqY",
                  shareHeading: "",
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-tZAHB.framer-14ji77b, .framer-tZAHB .framer-14ji77b { display: block; }",
  ".framer-tZAHB.framer-ys531d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-tZAHB .framer-13yahkw-container { flex: none; height: 20px; position: relative; width: 77px; z-index: 0; }",
  ".framer-tZAHB .framer-1jcirej-container { flex: none; height: auto; left: 49%; position: absolute; top: 50%; width: auto; z-index: 1; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 20
 * @framerIntrinsicWidth 77
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"xtLiTzMjk":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerQhLe9Cy4m = withCSS(Component, css, "framer-tZAHB");
export default FramerQhLe9Cy4m;
FramerQhLe9Cy4m.displayName = "Share Linkedin";
FramerQhLe9Cy4m.defaultProps = { height: 20, width: 77 };
addFonts(
  FramerQhLe9Cy4m,
  [
    { explicitInter: true, fonts: [] },
    ...Redes_Blog_ArticleFonts,
    ...SocialMediaShareButtonsFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerQhLe9Cy4m",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "20",
        framerIntrinsicWidth: "77",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"xtLiTzMjk":{"layout":["auto","auto"]}}}',
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./QhLe9Cy4m.map
