// Generated by Framer (c85c929)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { Lottie } from "https://framerusercontent.com/modules/YbkSqZ7STzW5WsMb1yan/RLfsHd78NBd0kbafA9hd/Lottie.js";
const LottieFonts = getFonts(Lottie);
const cycleOrder = ["Z9yIKBKcA", "Z8J9yTuB4"];
const serializationHash = "framer-PAQOR";
const variantClassNames = {
  Z8J9yTuB4: "framer-v-1gp0qrj",
  Z9yIKBKcA: "framer-v-p6f942",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { play: "Z8J9yTuB4", stop: "Z9yIKBKcA" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Z9yIKBKcA",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Z9yIKBKcA",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-p6f942",
            className,
            classNames
          ),
          "data-framer-name": "stop",
          layoutDependency: layoutDependency,
          layoutId: "Z9yIKBKcA",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { Z8J9yTuB4: { "data-framer-name": "play" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-1nc59ry-container",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "UX0JHapDl-container",
              nodeId: "UX0JHapDl",
              rendersWithMotion: true,
              scopeId: "Zc91IjOKU",
              children: /*#__PURE__*/ _jsx(Lottie, {
                height: "100%",
                id: "UX0JHapDl",
                isForwardsDirection: true,
                layoutId: "UX0JHapDl",
                loop: false,
                pauseOnCanvas: true,
                playing: false,
                poster: "Auto",
                posterProgress: 0,
                progress: 0,
                speed: 1,
                srcFile:
                  "https://framerusercontent.com/assets/exPwnwgL7IYeYgGwzofJK7Y0eo.json",
                srcType: "Upload",
                srcUrl: "https://misc.framerstatic.com/lottie/logo.json",
                style: { height: "100%", width: "100%" },
                width: "100%",
                ...addPropertyOverrides(
                  { Z8J9yTuB4: { playing: true } },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-PAQOR.framer-19zf4qw, .framer-PAQOR .framer-19zf4qw { display: block; }",
  ".framer-PAQOR.framer-p6f942 { height: 130px; overflow: hidden; position: relative; width: 156px; }",
  ".framer-PAQOR .framer-1nc59ry-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
  ".framer-PAQOR.framer-v-1gp0qrj.framer-p6f942 { height: 241px; width: 279px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 130
 * @framerIntrinsicWidth 156
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Z8J9yTuB4":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerZc91IjOKU = withCSS(Component, css, "framer-PAQOR");
export default FramerZc91IjOKU;
FramerZc91IjOKU.displayName = "Loti st 3 blockchain";
FramerZc91IjOKU.defaultProps = { height: 130, width: 156 };
addPropertyControls(FramerZc91IjOKU, {
  variant: {
    options: ["Z9yIKBKcA", "Z8J9yTuB4"],
    optionTitles: ["stop", "play"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerZc91IjOKU,
  [{ explicitInter: true, fonts: [] }, ...LottieFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerZc91IjOKU",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "130",
        framerContractVersion: "1",
        framerIntrinsicWidth: "156",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Z8J9yTuB4":{"layout":["fixed","fixed"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Zc91IjOKU.map
