// Generated by Framer (ee1e8a0)
import { jsx as _jsx } from "react/jsx-runtime";
import { cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.img, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("img", { ...rest, ref: ref });
});
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    alt: "",
    className: cx("framer-v1R08", className),
    layoutId: layoutId,
    ref: ref,
    src: 'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 249 251" xmlns="http://www.w3.org/2000/svg"><path d="M 116.627 250.9 C 84.371 250.9 56.866 238.755 34.119 214.466 C 11.374 190.038 0 160.435 0 125.657 C 0 90.879 11.374 61.276 34.119 36.848 C 56.866 12.283 84.435 0 116.832 0 C 148.128 0 174.667 11.248 196.441 33.743 L 196.441 7.867 L 248.347 7.867 L 248.347 243.034 L 222.5 243.034 L 196.441 243.034 L 196.441 217.364 C 174.384 239.583 147.782 250.763 116.627 250.9 Z M 125.93 51.132 C 106.216 51.132 89.742 58.309 76.508 72.662 C 63.276 86.877 56.659 104.542 56.659 125.657 C 56.659 146.634 63.276 164.231 76.508 178.446 C 89.742 192.66 106.146 199.768 125.725 199.768 C 145.439 199.768 161.913 192.66 175.147 178.446 C 188.515 164.231 195.206 146.566 195.206 125.45 C 195.206 104.335 188.586 86.67 175.351 72.455 C 162.117 58.24 145.643 51.132 125.93 51.132 Z" fill="rgb(198, 241, 157)" height="250.90014062px" id="KvjiUeDpO" transform="translate(0 0.006)" width="248.347px"/></svg>',
    style: { ...style },
  });
});
const css = [
  `.framer-v1R08 { -webkit-mask: ${mask}; aspect-ratio: 0.9920318725099602; display: block; mask: ${mask}; user-select: none; width: 249px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 249
 * @framerIntrinsicHeight 251
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"a","color":{"type":"static","value":"rgb(198,241,157)"},"set":{"localId":"vectorSet/bmfFBxgX1","id":"bmfFBxgX1","moduleId":"6fa1cjluBWQTIt8s7uDz"}}
 */ const Icon = withCSS(Component, css, "framer-v1R08");
Icon.displayName = "a";
export default Icon;
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"a","color":{"type":"static","value":"rgb(198,241,157)"},"set":{"localId":"vectorSet/bmfFBxgX1","id":"bmfFBxgX1","moduleId":"6fa1cjluBWQTIt8s7uDz"}}',
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "251",
        framerContractVersion: "1",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerIntrinsicWidth: "249",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
