// Generated by Framer (9e0d514)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  FormContainer,
  FormPlainTextInput,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useRouteElementId,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Lenis from "https://framerusercontent.com/modules/bSeEZJm22jsjERCOGQvq/VB8afRw6VQVsqyyipLnz/Lenis.js";
import BTN_Redes_Contact from "#framer/local/canvasComponent/lSOdjv5fT/lSOdjv5fT.js";
import BadgeTitle from "#framer/local/canvasComponent/m8mchcvpq/m8mchcvpq.js";
import Select from "#framer/local/canvasComponent/MZv440NaL/MZv440NaL.js";
import Button from "#framer/local/canvasComponent/yE2QfUzJH/yE2QfUzJH.js";
import * as sharedStyle2 from "#framer/local/css/IOQroGfcd/IOQroGfcd.js";
import * as sharedStyle1 from "#framer/local/css/lF0UT5hyI/lF0UT5hyI.js";
import * as sharedStyle from "#framer/local/css/lxwtqyXJR/lxwtqyXJR.js";
import metadataProvider from "#framer/local/webPageMetadata/nKp0lj3hZ/nKp0lj3hZ.js";
const LenisFonts = getFonts(Lenis);
const BadgeTitleFonts = getFonts(BadgeTitle);
const BTN_Redes_ContactFonts = getFonts(BTN_Redes_Contact);
const SelectFonts = getFonts(Select);
const ButtonFonts = getFonts(Button);
const breakpoints = {
  B4IoPMiID: "(max-width: 959.98px)",
  bZTdoSamU: "(min-width: 960px) and (max-width: 1439.98px)",
  wUFp2elBG: "(min-width: 1440px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-n8eK1";
const variantClassNames = {
  B4IoPMiID: "framer-v-172cj67",
  bZTdoSamU: "framer-v-13am3tj",
  wUFp2elBG: "framer-v-ujuyzw",
};
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const formVariants = (form, variants, currentVariant) => {
  switch (form.state) {
    case "success":
      return variants.success ?? currentVariant;
    case "pending":
      return variants.pending ?? currentVariant;
    case "error":
      return variants.error ?? currentVariant;
    case "incomplete":
      return variants.incomplete ?? currentVariant;
    default:
      return currentVariant;
  }
};
const humanReadableVariantMap = {
  "Small DSK": "bZTdoSamU",
  Desktop: "wUFp2elBG",
  Phone: "B4IoPMiID",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "wUFp2elBG",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const elementId = useRouteElementId("mFyxXVsrv");
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (!isBrowser()) return true;
    if (baseVariant === "B4IoPMiID") return false;
    return true;
  };
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "wUFp2elBG",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-ujuyzw", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(Container, {
                className: "framer-96mjsf-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layout: motionLayout,
                nodeId: "KEAHi8JVr",
                scopeId: "nKp0lj3hZ",
                children: /*#__PURE__*/ _jsx(Lenis, {
                  height: "100%",
                  id: "KEAHi8JVr",
                  infinite: false,
                  intensity: 12,
                  layoutId: "KEAHi8JVr",
                  orientation: "vertical",
                  smooth: true,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-68zmzx",
              "data-framer-name": "Content",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-qeg3l0",
                  "data-framer-name": "L",
                  children: [
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-pbb4sa",
                      id: elementId,
                      ref: ref1,
                      children: [
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 24,
                          children: /*#__PURE__*/ _jsx(Container, {
                            className: "framer-nk9sid-container",
                            nodeId: "rYI7I9xpV",
                            scopeId: "nKp0lj3hZ",
                            children: /*#__PURE__*/ _jsx(BadgeTitle, {
                              gcVlh98w5: "say hi",
                              height: "100%",
                              id: "rYI7I9xpV",
                              layoutId: "rYI7I9xpV",
                              variant: matchVariant("xdy29zwVa"),
                              width: "100%",
                            }),
                          }),
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h1", {
                              className: "framer-styles-preset-1schlan",
                              "data-styles-preset": "lxwtqyXJR",
                              children: "Let’s Talk",
                            }),
                          }),
                          className: "framer-pc3tjk",
                          "data-framer-name": "Let’s Talk",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx("p", {
                          className: "framer-styles-preset-1kigr86",
                          "data-styles-preset": "lF0UT5hyI",
                          children:
                            "Whether you’re ready to start measuring impact or just exploring options, we’d love to connect.",
                        }),
                      }),
                      className: "framer-6r8di4",
                      "data-framer-name":
                        "Whether you’re ready to start measuring impact or just exploring options, we’d love to connect.",
                      fonts: ["Inter"],
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    isDisplayed() &&
                      /*#__PURE__*/ _jsxs("div", {
                        className: "framer-jy7dqv hidden-172cj67",
                        "data-framer-name": "Redes",
                        children: [
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 19,
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-1hc1tmp-container",
                              nodeId: "sWxwcQBC5",
                              scopeId: "nKp0lj3hZ",
                              children: /*#__PURE__*/ _jsx(BTN_Redes_Contact, {
                                height: "100%",
                                id: "sWxwcQBC5",
                                IN_NQt8n6: "Linkedin",
                                layoutId: "sWxwcQBC5",
                                s0JWxFmmy:
                                  "https://www.linkedin.com/authwall?trk=bf&trkInfo=AQHSXMiKbobX2QAAAZhDFnEo-klIv197fSKbLBa2nssPL-rM-IA1WlJZhivFpRbSbbCjvG1VXv8sCWTtHhz3NvWG4Pn413I5b1Q5KscIl0b0HTaIwwg3u1JNniTx45d37FQH2F4=&original_referer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fprakritiearth%2F",
                                width: "100%",
                              }),
                            }),
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 19,
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-1itcrag-container",
                              nodeId: "zFMdFKhuR",
                              scopeId: "nKp0lj3hZ",
                              children: /*#__PURE__*/ _jsx(BTN_Redes_Contact, {
                                height: "100%",
                                id: "zFMdFKhuR",
                                IN_NQt8n6: "Instagram",
                                layoutId: "zFMdFKhuR",
                                s0JWxFmmy:
                                  "https://www.instagram.com/prakritiearth/?igsh=Nm9iM2FieXc2aDdo#",
                                width: "100%",
                              }),
                            }),
                          }),
                        ],
                      }),
                  ],
                }),
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-1ccmp4a",
                  "data-framer-name": "R",
                  children: /*#__PURE__*/ _jsx(FormContainer, {
                    action:
                      "https://api.framer.com/forms/v1/forms/46faf8af-fdc4-4d93-8e04-407d1e65938c/submit",
                    className: "framer-nj4d6p",
                    nodeId: "rmGtUp7wr",
                    children: (formState) =>
                      /*#__PURE__*/ _jsxs(_Fragment, {
                        children: [
                          /*#__PURE__*/ _jsxs("div", {
                            className: "framer-n1zp1f",
                            "data-framer-name": "Radio",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("p", {
                                    className: "framer-styles-preset-7ilx2o",
                                    "data-styles-preset": "IOQroGfcd",
                                    children: "Reason of contact",
                                  }),
                                }),
                                className: "framer-16z4kpo",
                                "data-framer-name": "Personal info",
                                fonts: ["Inter"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsxs("div", {
                                className: "framer-s7gouw",
                                children: [
                                  /*#__PURE__*/ _jsx(
                                    ComponentViewportProvider,
                                    {
                                      height: 45,
                                      children: /*#__PURE__*/ _jsx(Container, {
                                        className: "framer-t0lcs5-container",
                                        nodeId: "riqSwkskG",
                                        scopeId: "nKp0lj3hZ",
                                        children: /*#__PURE__*/ _jsx(Select, {
                                          height: "100%",
                                          id: "riqSwkskG",
                                          layoutId: "riqSwkskG",
                                          MRmUXkKNc: "Partnership",
                                          width: "100%",
                                        }),
                                      }),
                                    }
                                  ),
                                  /*#__PURE__*/ _jsx(
                                    ComponentViewportProvider,
                                    {
                                      height: 45,
                                      children: /*#__PURE__*/ _jsx(Container, {
                                        className: "framer-5qm7z7-container",
                                        nodeId: "dqSrQ40aE",
                                        scopeId: "nKp0lj3hZ",
                                        children: /*#__PURE__*/ _jsx(Select, {
                                          height: "100%",
                                          id: "dqSrQ40aE",
                                          layoutId: "dqSrQ40aE",
                                          MRmUXkKNc: "Business",
                                          width: "100%",
                                        }),
                                      }),
                                    }
                                  ),
                                  /*#__PURE__*/ _jsx(
                                    ComponentViewportProvider,
                                    {
                                      height: 45,
                                      children: /*#__PURE__*/ _jsx(Container, {
                                        className: "framer-1vybccs-container",
                                        nodeId: "w7EOy_BCv",
                                        scopeId: "nKp0lj3hZ",
                                        children: /*#__PURE__*/ _jsx(Select, {
                                          height: "100%",
                                          id: "w7EOy_BCv",
                                          layoutId: "w7EOy_BCv",
                                          MRmUXkKNc: "Media",
                                          width: "100%",
                                        }),
                                      }),
                                    }
                                  ),
                                  /*#__PURE__*/ _jsx(
                                    ComponentViewportProvider,
                                    {
                                      height: 45,
                                      children: /*#__PURE__*/ _jsx(Container, {
                                        className: "framer-1vsqt1c-container",
                                        nodeId: "TWCh7N0A0",
                                        scopeId: "nKp0lj3hZ",
                                        children: /*#__PURE__*/ _jsx(Select, {
                                          height: "100%",
                                          id: "TWCh7N0A0",
                                          layoutId: "TWCh7N0A0",
                                          MRmUXkKNc: "Careers",
                                          width: "100%",
                                        }),
                                      }),
                                    }
                                  ),
                                  /*#__PURE__*/ _jsx(
                                    ComponentViewportProvider,
                                    {
                                      height: 45,
                                      children: /*#__PURE__*/ _jsx(Container, {
                                        className: "framer-zxw99g-container",
                                        nodeId: "Lx6WoJZZN",
                                        scopeId: "nKp0lj3hZ",
                                        children: /*#__PURE__*/ _jsx(Select, {
                                          height: "100%",
                                          id: "Lx6WoJZZN",
                                          layoutId: "Lx6WoJZZN",
                                          MRmUXkKNc: "Other",
                                          width: "100%",
                                        }),
                                      }),
                                    }
                                  ),
                                ],
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsxs("div", {
                            className: "framer-1t3sc61",
                            "data-framer-name": "Inputs",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("p", {
                                    className: "framer-styles-preset-7ilx2o",
                                    "data-styles-preset": "IOQroGfcd",
                                    children: "Personal info",
                                  }),
                                }),
                                className: "framer-u028vt",
                                "data-framer-name": "Personal info",
                                fonts: ["Inter"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsxs("div", {
                                className: "framer-jpp9ok",
                                "data-framer-name": "Data",
                                children: [
                                  /*#__PURE__*/ _jsxs("div", {
                                    className: "framer-1ar0tuy",
                                    children: [
                                      /*#__PURE__*/ _jsx("label", {
                                        className: "framer-1kskv7w",
                                        "data-framer-name": "First Name",
                                        children: /*#__PURE__*/ _jsx(
                                          FormPlainTextInput,
                                          {
                                            className: "framer-1f0pscm",
                                            inputName: "First Name",
                                            placeholder: "First Name",
                                            required: true,
                                            type: "text",
                                          }
                                        ),
                                      }),
                                      /*#__PURE__*/ _jsx("label", {
                                        className: "framer-12395qs",
                                        "data-framer-name": "Last Name",
                                        children: /*#__PURE__*/ _jsx(
                                          FormPlainTextInput,
                                          {
                                            className: "framer-1u550e7",
                                            inputName: "Email",
                                            placeholder: "Email",
                                            required: true,
                                            type: "email",
                                          }
                                        ),
                                      }),
                                    ],
                                  }),
                                  /*#__PURE__*/ _jsxs("div", {
                                    className: "framer-1tueufz",
                                    children: [
                                      /*#__PURE__*/ _jsx("label", {
                                        className: "framer-mpyl1x",
                                        "data-framer-name": "Email",
                                        children: /*#__PURE__*/ _jsx(
                                          FormPlainTextInput,
                                          {
                                            className: "framer-izdk15",
                                            inputName: "Last Name",
                                            placeholder: "Last Name",
                                            required: true,
                                            type: "text",
                                          }
                                        ),
                                      }),
                                      /*#__PURE__*/ _jsx("label", {
                                        className: "framer-rj8rcs",
                                        "data-framer-name": "Phone",
                                        children: /*#__PURE__*/ _jsx(
                                          FormPlainTextInput,
                                          {
                                            className: "framer-19xcyox",
                                            inputName: "Phone Number",
                                            placeholder: "Phone Number",
                                            required: true,
                                            type: "tel",
                                          }
                                        ),
                                      }),
                                    ],
                                  }),
                                ],
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsxs("label", {
                            className: "framer-1cgplok",
                            "data-framer-name": "Message",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("p", {
                                    className: "framer-styles-preset-7ilx2o",
                                    "data-styles-preset": "IOQroGfcd",
                                    children: "your message (optional)",
                                  }),
                                }),
                                className: "framer-1gzqe2s",
                                "data-framer-name": "Personal info",
                                fonts: ["Inter"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(FormPlainTextInput, {
                                className: "framer-vn2a8g",
                                inputName: "Message",
                                placeholder: "Write something",
                                type: "text",
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 58,
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-lcl6at-container",
                              nodeId: "QixlfXh1E",
                              scopeId: "nKp0lj3hZ",
                              children: /*#__PURE__*/ _jsx(Button, {
                                height: "100%",
                                id: "QixlfXh1E",
                                layoutId: "QixlfXh1E",
                                type: "submit",
                                variant: formVariants(
                                  formState,
                                  {
                                    pending: "qd4UgaKG3",
                                    success: "NvKg25vf5",
                                  },
                                  matchVariant("IT_tG5lTF")
                                ),
                                width: "100%",
                              }),
                            }),
                          }),
                        ],
                      }),
                  }),
                }),
              ],
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-n8eK1.framer-1k8rflk, .framer-n8eK1 .framer-1k8rflk { display: block; }",
  ".framer-n8eK1.framer-ujuyzw { align-content: center; align-items: center; background-color: var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
  ".framer-n8eK1 .framer-96mjsf-container, .framer-n8eK1 .framer-nk9sid-container, .framer-n8eK1 .framer-1hc1tmp-container, .framer-n8eK1 .framer-1itcrag-container, .framer-n8eK1 .framer-lcl6at-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-n8eK1 .framer-68zmzx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 131px 28px 234px 28px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-qeg3l0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 32%; }",
  ".framer-n8eK1 .framer-pbb4sa { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-pc3tjk, .framer-n8eK1 .framer-16z4kpo, .framer-n8eK1 .framer-u028vt, .framer-n8eK1 .framer-1gzqe2s { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-n8eK1 .framer-6r8di4 { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 81%; word-break: break-word; word-wrap: break-word; }",
  ".framer-n8eK1 .framer-jy7dqv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-n8eK1 .framer-1ccmp4a { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: visible; padding: 64px 0px 0px 0px; position: relative; width: 1px; }",
  ".framer-n8eK1 .framer-nj4d6p { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 86px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-n1zp1f, .framer-n8eK1 .framer-1cgplok { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-s7gouw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-t0lcs5-container, .framer-n8eK1 .framer-5qm7z7-container, .framer-n8eK1 .framer-1vybccs-container, .framer-n8eK1 .framer-1vsqt1c-container, .framer-n8eK1 .framer-zxw99g-container { cursor: pointer; flex: none; height: auto; position: relative; width: auto; }",
  ".framer-n8eK1 .framer-1t3sc61 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-jpp9ok { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-1ar0tuy, .framer-n8eK1 .framer-1tueufz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-n8eK1 .framer-1kskv7w, .framer-n8eK1 .framer-12395qs, .framer-n8eK1 .framer-mpyl1x, .framer-n8eK1 .framer-rj8rcs { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-1f0pscm, .framer-n8eK1 .framer-1u550e7, .framer-n8eK1 .framer-izdk15, .framer-n8eK1 .framer-19xcyox { --framer-input-border-bottom-width: 1px; --framer-input-border-color: rgba(15, 31, 16, 0.1); --framer-input-border-left-width: 0px; --framer-input-border-right-width: 0px; --framer-input-border-style: solid; --framer-input-border-top-width: 0px; --framer-input-focused-border-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 0px 0px 1px 0px; --framer-input-font-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-input-font-family: \"Geist Regular\"; --framer-input-font-letter-spacing: -0.01em; --framer-input-font-line-height: 120%; --framer-input-font-open-type-features: 'ss03' on, 'ss04' on; --framer-input-font-size: 18px; --framer-input-icon-color: #999999; --framer-input-padding: 16px 0px 16px 0px; --framer-input-placeholder-color: rgba(15, 31, 16, 0.6); flex: none; height: 50px; position: relative; width: 100%; }",
  ".framer-n8eK1 .framer-vn2a8g { --framer-input-border-bottom-width: 1px; --framer-input-border-color: rgba(15, 31, 16, 0.1); --framer-input-border-left-width: 0px; --framer-input-border-right-width: 0px; --framer-input-border-style: solid; --framer-input-border-top-width: 0px; --framer-input-focused-border-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 0px 0px 1px 0px; --framer-input-font-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-input-font-family: \"Geist Regular\"; --framer-input-font-letter-spacing: -0.01em; --framer-input-font-line-height: 120%; --framer-input-font-open-type-features: 'ss03' on, 'ss04' on; --framer-input-font-size: 18px; --framer-input-icon-color: #999999; --framer-input-padding: 16px 0px 16px 0px; --framer-input-placeholder-color: rgba(15, 31, 16, 0.6); --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  "@media (min-width: 960px) and (max-width: 1439.98px) { .framer-n8eK1.framer-ujuyzw { width: 960px; }}",
  "@media (max-width: 959.98px) { .framer-n8eK1.framer-ujuyzw { width: 390px; } .framer-n8eK1 .framer-68zmzx { flex-direction: column; gap: 0px; padding: 171px 16px 234px 16px; } .framer-n8eK1 .framer-qeg3l0 { width: 100%; } .framer-n8eK1 .framer-1ccmp4a, .framer-n8eK1 .framer-1ar0tuy, .framer-n8eK1 .framer-1tueufz { flex: none; width: 100%; } .framer-n8eK1 .framer-nj4d6p { gap: 72px; } .framer-n8eK1 .framer-s7gouw { flex-wrap: wrap; gap: 12px 10px; } .framer-n8eK1 .framer-jpp9ok { flex-direction: column; justify-content: flex-start; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1925
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bZTdoSamU":{"layout":["fixed","auto"]},"B4IoPMiID":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"mFyxXVsrv":{"pattern":":mFyxXVsrv","name":"sds"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramernKp0lj3hZ = withCSS(Component, css, "framer-n8eK1");
export default FramernKp0lj3hZ;
FramernKp0lj3hZ.displayName = "Page";
FramernKp0lj3hZ.defaultProps = { height: 1925, width: 1440 };
addFonts(
  FramernKp0lj3hZ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Geist Regular",
          source: "custom",
          style: "normal",
          uiFamilyName: "Geist",
          url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
          weight: "400",
        },
      ],
    },
    ...LenisFonts,
    ...BadgeTitleFonts,
    ...BTN_Redes_ContactFonts,
    ...SelectFonts,
    ...ButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramernKp0lj3hZ.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(BadgeTitle, {}, context),
      forwardLoader(BTN_Redes_Contact, {}, context),
      forwardLoader(Select, {}, context),
      forwardLoader(Button, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramernKp0lj3hZ",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "1440",
        framerAcceptsLayoutTemplate: "true",
        framerResponsiveScreen: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bZTdoSamU":{"layout":["fixed","auto"]},"B4IoPMiID":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "1925",
        framerScrollSections:
          '{"mFyxXVsrv":{"pattern":":mFyxXVsrv","name":"sds"}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
