// Generated by Framer (9e0d514)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getPropertyControls,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import StepNumber from "https://framerusercontent.com/modules/8nF9SekezJifjmwJQIs9/sgp24FR3UCs1I6APV9k3/aFcwcQlrP.js";
const StepNumberFonts = getFonts(StepNumber);
const StepNumberControls = getPropertyControls(StepNumber);
const cycleOrder = ["psJXSV7xC", "awp8SRw2x"];
const serializationHash = "framer-a76hS";
const variantClassNames = {
  awp8SRw2x: "framer-v-164e45s",
  psJXSV7xC: "framer-v-pjzlki",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const kYxiSos93 = undefined;
const QUUXxlNBg = undefined;
const GArhSIUTO = undefined;
const lqhq3Sagy = undefined;
const psZS5XMR0 = undefined;
const eVXVZz3OF = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { "Variant 1": "psJXSV7xC", mob: "awp8SRw2x" };
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = {
  "Variant 1": "XAr2kUzZk",
  mob: "T_riQyuEa",
  XL: "X7Mw3200t",
};
const getProps = ({
  contentSize,
  descrip,
  height,
  id,
  stepNumber,
  title,
  titleSize,
  variant1,
  width,
  ...props
}) => {
  return {
    ...props,
    eVXVZz3OF:
      descrip ??
      props.eVXVZz3OF ??
      "Prakriti’s towers record GHG signals 10x per second—capturing continuous ecosystem data.",
    GArhSIUTO: titleSize ?? props.GArhSIUTO ?? 40,
    kYxiSos93:
      humanReadableEnumMap[variant1] ??
      variant1 ??
      props.kYxiSos93 ??
      "XAr2kUzZk",
    lqhq3Sagy:
      title ?? props.lqhq3Sagy ?? "High-Frequency Atmospheric Monitoring",
    psZS5XMR0: contentSize ?? props.psZS5XMR0 ?? 20,
    QUUXxlNBg: stepNumber ?? props.QUUXxlNBg ?? "01",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "psJXSV7xC",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    lqhq3Sagy,
    eVXVZz3OF,
    QUUXxlNBg,
    GArhSIUTO,
    psZS5XMR0,
    kYxiSos93,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "psJXSV7xC",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-pjzlki",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "psJXSV7xC",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { awp8SRw2x: { "data-framer-name": "mob" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 54,
              y: (componentViewport?.y || 0) + 0,
              ...addPropertyOverrides(
                { awp8SRw2x: { y: undefined } },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1cbt9ls-container",
                layoutDependency: layoutDependency,
                layoutId: "g1c4cYGvR-container",
                nodeId: "g1c4cYGvR",
                rendersWithMotion: true,
                scopeId: "So6DSECmy",
                children: /*#__PURE__*/ _jsx(StepNumber, {
                  height: "100%",
                  id: "g1c4cYGvR",
                  layoutId: "g1c4cYGvR",
                  SYWhBdMj7: QUUXxlNBg,
                  variant: matchVariant(kYxiSos93),
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-16rgq93",
              "data-framer-name": "Frame 1000006533",
              layoutDependency: layoutDependency,
              layoutId: "EIEutw4lI",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h4, {
                      dir: "auto",
                      style: {
                        "--font-selector": "Q1VTVE9NVjI7R2Vpc3QgTWVkaXVt",
                        "--framer-font-family":
                          '"Geist Medium", "Geist Medium Placeholder", sans-serif',
                        "--framer-font-open-type-features":
                          "'ss03' on, 'ss06' on",
                        "--framer-font-size":
                          "calc(var(--variable-reference-GArhSIUTO-So6DSECmy) * 1px)",
                        "--framer-font-weight": "500",
                        "--framer-letter-spacing": "-0.03em",
                        "--framer-line-height": "95%",
                        "--framer-text-color":
                          "var(--extracted-1eung3n, var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)))",
                      },
                      children: "High-Frequency Atmospheric Monitoring",
                    }),
                  }),
                  className: "framer-8q5twz",
                  "data-framer-name": "High-Frequency Atmospheric Monitoring",
                  fonts: ["CUSTOMV2;Geist Medium"],
                  layoutDependency: layoutDependency,
                  layoutId: "q35dv0qpk",
                  style: {
                    "--extracted-1eung3n":
                      "var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                    "--variable-reference-GArhSIUTO-So6DSECmy": GArhSIUTO,
                  },
                  text: lqhq3Sagy,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
                        "--framer-font-family":
                          '"Geist Regular", "Geist Regular Placeholder", sans-serif',
                        "--framer-font-open-type-features":
                          "'ss03' on, 'ss06' on",
                        "--framer-font-size":
                          "calc(var(--variable-reference-psZS5XMR0-So6DSECmy) * 1px)",
                        "--framer-letter-spacing": "-0.02em",
                        "--framer-line-height": "120%",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)))",
                      },
                      children:
                        "Prakriti’s towers record GHG signals 10x per second—capturing continuous ecosystem data.",
                    }),
                  }),
                  className: "framer-vedxw2",
                  "data-framer-name":
                    "Prakriti’s towers record GHG signals 10x per second—capturing continuous ecosystem data.",
                  fonts: ["CUSTOM;Geist Regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "GnJcWZ2ZI",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                    "--variable-reference-psZS5XMR0-So6DSECmy": psZS5XMR0,
                  },
                  text: eVXVZz3OF,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-a76hS.framer-9jjqqg, .framer-a76hS .framer-9jjqqg { display: block; }",
  ".framer-a76hS.framer-pjzlki { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 583px; }",
  ".framer-a76hS .framer-1cbt9ls-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-a76hS .framer-16rgq93 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-a76hS .framer-8q5twz { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-a76hS .framer-vedxw2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 92%; word-break: break-word; word-wrap: break-word; }",
  ".framer-a76hS.framer-v-164e45s.framer-pjzlki { flex-direction: column; gap: 20px; }",
  ".framer-a76hS.framer-v-164e45s .framer-16rgq93 { flex: none; width: 100%; }",
  ".framer-a76hS.framer-v-164e45s .framer-vedxw2 { width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 144
 * @framerIntrinsicWidth 583
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"awp8SRw2x":{"layout":["fixed","auto"]}}}
 * @framerVariables {"lqhq3Sagy":"title","eVXVZz3OF":"descrip","QUUXxlNBg":"stepNumber","GArhSIUTO":"titleSize","psZS5XMR0":"contentSize","kYxiSos93":"variant1"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerSo6DSECmy = withCSS(Component, css, "framer-a76hS");
export default FramerSo6DSECmy;
FramerSo6DSECmy.displayName = "Step";
FramerSo6DSECmy.defaultProps = { height: 144, width: 583 };
addPropertyControls(FramerSo6DSECmy, {
  variant: {
    options: ["psJXSV7xC", "awp8SRw2x"],
    optionTitles: ["Variant 1", "mob"],
    title: "Variant",
    type: ControlType.Enum,
  },
  lqhq3Sagy: {
    defaultValue: "High-Frequency Atmospheric Monitoring",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onlqhq3SagyChange: { changes: "lqhq3Sagy", type: ControlType.ChangeHandler },
  eVXVZz3OF: {
    defaultValue:
      "Prakriti’s towers record GHG signals 10x per second—capturing continuous ecosystem data.",
    displayTextArea: false,
    title: "descrip",
    type: ControlType.String,
  },
  oneVXVZz3OFChange: { changes: "eVXVZz3OF", type: ControlType.ChangeHandler },
  QUUXxlNBg: {
    defaultValue: "01",
    title: "step number",
    type: ControlType.String,
  },
  onQUUXxlNBgChange: { changes: "QUUXxlNBg", type: ControlType.ChangeHandler },
  GArhSIUTO: {
    defaultValue: 40,
    title: "Title size",
    type: ControlType.Number,
  },
  onGArhSIUTOChange: { changes: "GArhSIUTO", type: ControlType.ChangeHandler },
  psZS5XMR0: {
    defaultValue: 20,
    title: "content size",
    type: ControlType.Number,
  },
  onpsZS5XMR0Change: { changes: "psZS5XMR0", type: ControlType.ChangeHandler },
  kYxiSos93: StepNumberControls?.["variant"] && {
    ...StepNumberControls["variant"],
    defaultValue: "XAr2kUzZk",
    description: undefined,
    hidden: undefined,
    title: "Variant",
  },
  onkYxiSos93Change: { changes: "kYxiSos93", type: ControlType.ChangeHandler },
});
addFonts(
  FramerSo6DSECmy,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Geist Medium",
          source: "custom",
          style: "normal",
          uiFamilyName: "Geist",
          url: "https://framerusercontent.com/assets/dNqH0c4qjo3RGmYZnJknwKtT0.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Geist Regular",
          source: "custom",
          style: "normal",
          uiFamilyName: "Geist",
          url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
          weight: "400",
        },
      ],
    },
    ...StepNumberFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerSo6DSECmy.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(StepNumber, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerSo6DSECmy",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerVariables:
          '{"lqhq3Sagy":"title","eVXVZz3OF":"descrip","QUUXxlNBg":"stepNumber","GArhSIUTO":"titleSize","psZS5XMR0":"contentSize","kYxiSos93":"variant1"}',
        framerContractVersion: "1",
        framerIntrinsicHeight: "144",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"awp8SRw2x":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "583",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./So6DSECmy.map
