// Generated by Framer (9e04080)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-KKdRq .framer-styles-preset-1hhps5v:not(.rich-text-wrapper), .framer-KKdRq .framer-styles-preset-1hhps5v.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: #0088ff; --framer-link-hover-text-decoration: underline; --framer-link-text-color: #0099ff; --framer-link-text-decoration: none; }",
];
export const className = "framer-KKdRq";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
