// Generated by Framer (a4aa1f7)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import BadgeTitle from "https://framerusercontent.com/modules/65xOV4PZCF65hiAlop35/Vy37RbJ7gzcHrSYdYgOB/m8mchcvpq.js";
const BadgeTitleFonts = getFonts(BadgeTitle);
const cycleOrder = ["UH6K7tcT4", "nJF3QCMDl"];
const serializationHash = "framer-qwUei";
const variantClassNames = {
  nJF3QCMDl: "framer-v-12y802x",
  UH6K7tcT4: "framer-v-1w8dawp",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { "Variant 1": "UH6K7tcT4", mob: "nJF3QCMDl" };
const getProps = ({ height, id, text, title, width, ...props }) => {
  return {
    ...props,
    frsL4Tvax: title ?? props.frsL4Tvax ?? "Continuous Monitoring",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "UH6K7tcT4",
    zjF8S3vNb:
      text ??
      props.zjF8S3vNb ??
      "Sensor-based observation updated every 10 seconds",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    frsL4Tvax,
    zjF8S3vNb,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "UH6K7tcT4",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1w8dawp",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "UH6K7tcT4",
          ref: refBinding,
          style: {
            backdropFilter: "blur(11.5px)",
            backgroundColor: "rgba(255, 255, 255, 0.1)",
            borderBottomLeftRadius: 12,
            borderBottomRightRadius: 12,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            WebkitBackdropFilter: "blur(11.5px)",
            ...style,
          },
          ...addPropertyOverrides(
            { nJF3QCMDl: { "data-framer-name": "mob" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 24,
              y: (componentViewport?.y || 0) + 12 + 0,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-k5w1fw-container",
                layoutDependency: layoutDependency,
                layoutId: "Da4sAcs0v-container",
                nodeId: "Da4sAcs0v",
                rendersWithMotion: true,
                scopeId: "F0El9FnGd",
                children: /*#__PURE__*/ _jsx(BadgeTitle, {
                  gcVlh98w5: frsL4Tvax,
                  height: "100%",
                  id: "Da4sAcs0v",
                  layoutId: "Da4sAcs0v",
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Geist", "Geist Placeholder", sans-serif',
                    "--framer-font-size": "18px",
                    "--framer-letter-spacing": "-0.01em",
                    "--framer-line-height": "120%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children: "Sensor-based observation updated every 10 seconds",
                }),
              }),
              className: "framer-w20fz9",
              "data-framer-name":
                "Sensor-based observation updated every 10 seconds",
              fonts: ["GF;Geist-regular"],
              layoutDependency: layoutDependency,
              layoutId: "vFhDfF8qi",
              style: {
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: zjF8S3vNb,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  nJF3QCMDl: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-letter-spacing": "-0.01em",
                          "--framer-line-height": "120%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                        },
                        children:
                          "Sensor-based observation updated every 10 seconds",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-qwUei.framer-1n0or28, .framer-qwUei .framer-1n0or28 { display: block; }",
  ".framer-qwUei.framer-1w8dawp { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px; position: relative; width: 333px; }",
  ".framer-qwUei .framer-k5w1fw-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-qwUei .framer-w20fz9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 108
 * @framerIntrinsicWidth 333
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"nJF3QCMDl":{"layout":["fixed","auto"]}}}
 * @framerVariables {"frsL4Tvax":"title","zjF8S3vNb":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerF0El9FnGd = withCSS(Component, css, "framer-qwUei");
export default FramerF0El9FnGd;
FramerF0El9FnGd.displayName = "amrv Tooltip";
FramerF0El9FnGd.defaultProps = { height: 108, width: 333 };
addPropertyControls(FramerF0El9FnGd, {
  variant: {
    options: ["UH6K7tcT4", "nJF3QCMDl"],
    optionTitles: ["Variant 1", "mob"],
    title: "Variant",
    type: ControlType.Enum,
  },
  frsL4Tvax: {
    defaultValue: "Continuous Monitoring",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  zjF8S3vNb: {
    defaultValue: "Sensor-based observation updated every 10 seconds",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
});
addFonts(
  FramerF0El9FnGd,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
          weight: "400",
        },
      ],
    },
    ...BadgeTitleFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerF0El9FnGd",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerVariables: '{"frsL4Tvax":"title","zjF8S3vNb":"text"}',
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"nJF3QCMDl":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "108",
        framerIntrinsicWidth: "333",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
