// Generated by Framer (8f9ffef)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const MotionDivWithFX = withFX(motion.div);
const MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(motion.div)
);
const enabledGestures = { MEJ3Y8zdL: { hover: true } };
const cycleOrder = ["MEJ3Y8zdL", "yXat1nZyE", "PiVHDXoqO"];
const serializationHash = "framer-ZCeD1";
const variantClassNames = {
  MEJ3Y8zdL: "framer-v-12qrghh",
  PiVHDXoqO: "framer-v-j1ji3q",
  yXat1nZyE: "framer-v-ulhk5i",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { duration: 0, type: "tween" };
const transition2 = {
  delay: 0,
  duration: 0.3,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transition3 = {
  delay: 0,
  duration: 1,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation2 = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Default: "MEJ3Y8zdL",
  Hidden: "PiVHDXoqO",
  Loading: "yXat1nZyE",
};
const getProps = ({ click, height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "MEJ3Y8zdL",
    Wld3NDzSj: click ?? props.Wld3NDzSj,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, Wld3NDzSj, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "MEJ3Y8zdL",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapn9xadi = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (Wld3NDzSj) {
      const res = await Wld3NDzSj(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const isDisplayed = () => {
    if (baseVariant === "PiVHDXoqO") return false;
    return true;
  };
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed1 = () => {
    if (baseVariant === "yXat1nZyE") return false;
    return true;
  };
  const isDisplayed2 = () => {
    if (baseVariant === "yXat1nZyE") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children:
        isDisplayed() &&
        /*#__PURE__*/ _jsx(Transition, {
          value: transition1,
          children: /*#__PURE__*/ _jsxs(motion.button, {
            ...restProps,
            ...gestureHandlers,
            className: cx(
              scopingClassNames,
              "framer-12qrghh",
              className,
              classNames
            ),
            "data-framer-name": "Default",
            "data-highlight": true,
            "data-reset": "button",
            layoutDependency: layoutDependency,
            layoutId: "MEJ3Y8zdL",
            onTap: onTapn9xadi,
            ref: refBinding,
            style: {
              backgroundColor:
                "var(--token-4574eca4-72c6-4afc-909d-0f5a71c6a6f3, rgb(245, 244, 242))",
              borderBottomLeftRadius: 8,
              borderBottomRightRadius: 8,
              borderTopLeftRadius: 8,
              borderTopRightRadius: 8,
              ...style,
            },
            variants: {
              "MEJ3Y8zdL-hover": {
                backgroundColor:
                  "var(--token-29b0dbc5-7e1f-4b3e-8954-a3e1672ca3b5, rgb(198, 241, 157))",
              },
            },
            ...addPropertyOverrides(
              {
                "MEJ3Y8zdL-hover": { "data-framer-name": undefined },
                yXat1nZyE: { "data-framer-name": "Loading" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              isDisplayed1() &&
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-iz9nil",
                  "data-framer-name": "Load",
                  layoutDependency: layoutDependency,
                  layoutId: "I106:1163;106:1146",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7R2Vpc3QgTW9uby02MDA=",
                            "--framer-font-family": '"Geist Mono", monospace',
                            "--framer-font-size": "15px",
                            "--framer-font-weight": "600",
                            "--framer-line-height": "90%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(15, 31, 16))",
                            "--framer-text-transform": "uppercase",
                          },
                          children: "load more",
                        }),
                      }),
                      className: "framer-1d1n4sn",
                      "data-framer-name": "load more",
                      fonts: ["GF;Geist Mono-600"],
                      layoutDependency: layoutDependency,
                      layoutId: "I106:1163;106:1147",
                      style: {
                        "--extracted-r6o4lv": "rgb(15, 31, 16)",
                        "--framer-paragraph-spacing": "0px",
                      },
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(SVG, {
                      className: "framer-rxgvqm",
                      "data-framer-name": "Group 1000002752",
                      fill: "rgba(0,0,0,1)",
                      intrinsicHeight: 11,
                      intrinsicWidth: 11,
                      layoutDependency: layoutDependency,
                      layoutId: "I106:1163;106:1148",
                      svg: '<svg width="11" height="11" viewBox="0 0 11 11" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M11 5.49609L0 5.49609" stroke="#0F1F10" stroke-width="1.67" stroke-linecap="round"/>\n<path d="M5.50781 11L5.50781 0" stroke="#0F1F10" stroke-width="1.67" stroke-linecap="round"/>\n</svg>\n',
                      withExternalLayout: true,
                    }),
                  ],
                }),
              isDisplayed2() &&
                /*#__PURE__*/ _jsx(MotionDivWithFXWithOptimizedAppearEffect, {
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 1,
                  animate: animation,
                  className: "framer-2roqp3",
                  "data-framer-appear-id": "2roqp3",
                  "data-framer-name": "Spinner",
                  initial: animation1,
                  layoutDependency: layoutDependency,
                  layoutId: "Y6DEkBgoU",
                  optimized: true,
                  style: {
                    mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                    WebkitMask:
                      "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                  },
                  children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                    __framer__loop: animation2,
                    __framer__loopEffectEnabled: true,
                    __framer__loopRepeatDelay: 0,
                    __framer__loopRepeatType: "loop",
                    __framer__loopTransition: transition3,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: "framer-vsrqiu",
                    "data-framer-name": "Conic",
                    layoutDependency: layoutDependency,
                    layoutId: "M8M7PtNqY",
                    style: {
                      background:
                        "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)) 342deg)",
                    },
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1teig6a",
                      "data-framer-name": "Round",
                      layoutDependency: layoutDependency,
                      layoutId: "GPwXHQXRd",
                      style: {
                        backgroundColor:
                          "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                        borderBottomLeftRadius: 1,
                        borderBottomRightRadius: 1,
                        borderTopLeftRadius: 1,
                        borderTopRightRadius: 1,
                      },
                    }),
                  }),
                }),
            ],
          }),
        }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ZCeD1.framer-6gcjuz, .framer-ZCeD1 .framer-6gcjuz { display: block; }",
  ".framer-ZCeD1.framer-12qrghh { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 43px; justify-content: center; padding: 0px; position: relative; width: 142px; }",
  ".framer-ZCeD1 .framer-iz9nil { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ZCeD1 .framer-1d1n4sn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ZCeD1 .framer-rxgvqm { flex: none; height: 11px; position: relative; width: 11px; }",
  ".framer-ZCeD1 .framer-2roqp3 { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }",
  ".framer-ZCeD1 .framer-vsrqiu { bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
  ".framer-ZCeD1 .framer-1teig6a { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 43
 * @framerIntrinsicWidth 142
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"yXat1nZyE":{"layout":["fixed","fixed"]},"PiVHDXoqO":{"layout":["fixed","fixed"]},"GwWc6FltG":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"Wld3NDzSj":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerWVC651Vru = withCSS(Component, css, "framer-ZCeD1");
export default FramerWVC651Vru;
FramerWVC651Vru.displayName = "Load More";
FramerWVC651Vru.defaultProps = { height: 43, width: 142 };
addPropertyControls(FramerWVC651Vru, {
  variant: {
    options: ["MEJ3Y8zdL", "yXat1nZyE", "PiVHDXoqO"],
    optionTitles: ["Default", "Loading", "Hidden"],
    title: "Variant",
    type: ControlType.Enum,
  },
  Wld3NDzSj: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FramerWVC651Vru,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist Mono",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHjL55W7ihaO_CS.woff2",
          weight: "600",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerWVC651Vru",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"yXat1nZyE":{"layout":["fixed","fixed"]},"PiVHDXoqO":{"layout":["fixed","fixed"]},"GwWc6FltG":{"layout":["fixed","fixed"]}}}',
        framerVariables: '{"Wld3NDzSj":"click"}',
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "142",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "43",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./WVC651Vru.map
