// Generated by Framer (e0edd7a)
import { fontStore } from "framer";
fontStore.loadFonts(["GF;Geist Mono-500", "GF;Geist Mono-700"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Geist Mono",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
        weight: "500",
      },
      {
        family: "Geist Mono",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHaL55W7ihaO_CS.woff2",
        weight: "700",
      },
    ],
  },
];
export const css = [
  '.framer-yeTMi .framer-styles-preset-7ilx2o:not(.rich-text-wrapper), .framer-yeTMi .framer-styles-preset-7ilx2o.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
  '@media (max-width: 2559px) and (min-width: 1440px) { .framer-yeTMi .framer-styles-preset-7ilx2o:not(.rich-text-wrapper), .framer-yeTMi .framer-styles-preset-7ilx2o.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
  '@media (max-width: 1439px) and (min-width: 960px) { .framer-yeTMi .framer-styles-preset-7ilx2o:not(.rich-text-wrapper), .framer-yeTMi .framer-styles-preset-7ilx2o.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
  '@media (max-width: 959px) and (min-width: 0px) { .framer-yeTMi .framer-styles-preset-7ilx2o:not(.rich-text-wrapper), .framer-yeTMi .framer-styles-preset-7ilx2o.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
];
export const className = "framer-yeTMi";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
