// Generated by Framer (c85c929)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { Lottie } from "https://framerusercontent.com/modules/YbkSqZ7STzW5WsMb1yan/RLfsHd78NBd0kbafA9hd/Lottie.js";
const LottieFonts = getFonts(Lottie);
const cycleOrder = ["kVgXPdWRx", "mYWzBfh1R"];
const serializationHash = "framer-G8i61";
const variantClassNames = {
  kVgXPdWRx: "framer-v-1wvoems",
  mYWzBfh1R: "framer-v-1oqt2u4",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { pause: "kVgXPdWRx", play: "mYWzBfh1R" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "kVgXPdWRx",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "kVgXPdWRx",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1wvoems",
            className,
            classNames
          ),
          "data-framer-name": "pause",
          layoutDependency: layoutDependency,
          layoutId: "kVgXPdWRx",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { mYWzBfh1R: { "data-framer-name": "play" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-rh8acs-container",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "MGe6kHLEI-container",
              nodeId: "MGe6kHLEI",
              rendersWithMotion: true,
              scopeId: "OITra1nZ4",
              children: /*#__PURE__*/ _jsx(Lottie, {
                height: "100%",
                id: "MGe6kHLEI",
                isForwardsDirection: true,
                layoutId: "MGe6kHLEI",
                loop: false,
                pauseOnCanvas: true,
                playing: false,
                poster: "Auto",
                posterProgress: 0,
                progress: 0,
                speed: 1,
                srcFile:
                  "https://framerusercontent.com/assets/8viA6joDkEwpAiPdW7yrlMNSGA0.json",
                srcType: "Upload",
                srcUrl: "https://misc.framerstatic.com/lottie/logo.json",
                style: { height: "100%", width: "100%" },
                width: "100%",
                ...addPropertyOverrides(
                  { mYWzBfh1R: { playing: true } },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-G8i61.framer-1hncf1j, .framer-G8i61 .framer-1hncf1j { display: block; }",
  ".framer-G8i61.framer-1wvoems { height: 200px; overflow: visible; position: relative; width: 684px; }",
  ".framer-G8i61 .framer-rh8acs-container { bottom: 0px; flex: none; height: 100%; position: absolute; right: 0px; width: 100%; }",
  ".framer-G8i61.framer-v-1oqt2u4.framer-1wvoems { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 684px); }",
  ".framer-G8i61.framer-v-1oqt2u4 .framer-rh8acs-container { aspect-ratio: 1.0474732006125573 / 1; height: var(--framer-aspect-ratio-supported, 653px); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 684
 * @framerIntrinsicWidth 684
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"mYWzBfh1R":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerOITra1nZ4 = withCSS(Component, css, "framer-G8i61");
export default FramerOITra1nZ4;
FramerOITra1nZ4.displayName = "Loti supply step 2";
FramerOITra1nZ4.defaultProps = { height: 684, width: 684 };
addPropertyControls(FramerOITra1nZ4, {
  variant: {
    options: ["kVgXPdWRx", "mYWzBfh1R"],
    optionTitles: ["pause", "play"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerOITra1nZ4,
  [{ explicitInter: true, fonts: [] }, ...LottieFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerOITra1nZ4",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"mYWzBfh1R":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "684",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "684",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./OITra1nZ4.map
