// Generated by Framer (ee1e8a0)
import { jsx as _jsx } from "react/jsx-runtime";
import { cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.img, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("img", { ...rest, ref: ref });
});
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    alt: "",
    className: cx("framer-o0wQz", className),
    layoutId: layoutId,
    ref: ref,
    src: 'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 57 314" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 0 313.626 L 28.332 313.626 L 56.452 313.626 L 56.452 0 L 28.127 0 Z" fill="rgb(198, 241, 157)" height="313.625938px" id="MaAmHkp1M" transform="translate(0.148 0.414)" width="56.451562px"/></svg>',
    style: { ...style },
  });
});
const css = [
  `.framer-o0wQz { -webkit-mask: ${mask}; aspect-ratio: 0.18152866242038215; display: block; mask: ${mask}; user-select: none; width: 57px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 57
 * @framerIntrinsicHeight 314
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"L","color":{"type":"static","value":"rgb(198,241,157)"},"set":{"localId":"vectorSet/bmfFBxgX1","id":"bmfFBxgX1","moduleId":"6fa1cjluBWQTIt8s7uDz"}}
 */ const Icon = withCSS(Component, css, "framer-o0wQz");
Icon.displayName = "L";
export default Icon;
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "314",
        framerIntrinsicWidth: "57",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerVector:
          '{"name":"L","color":{"type":"static","value":"rgb(198,241,157)"},"set":{"localId":"vectorSet/bmfFBxgX1","id":"bmfFBxgX1","moduleId":"6fa1cjluBWQTIt8s7uDz"}}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
