// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ZelIt30ALO921MYxWHXw/it5UzZWiNTEtsJnoElbb/pU1l54HaN.js";
import Vector from "https://framerusercontent.com/modules/axH8AWDBE94lY1vJTl58/PsfEzrKJ8B8OSVrRCZoz/fQS88Sh6B.js";
const VectorFonts = getFonts(Vector);
const enabledGestures = { LhN0vuRQJ: { hover: true } };
const serializationHash = "framer-TblLH";
const variantClassNames = { LhN0vuRQJ: "framer-v-smzgj0" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, width, ...props }) => {
  return { ...props, hhO8Dvlrl: link ?? props.hhO8Dvlrl };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, hhO8Dvlrl, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "LhN0vuRQJ",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: hhO8Dvlrl,
          motionChild: true,
          nodeId: "LhN0vuRQJ",
          openInNewTab: false,
          scopeId: "evj9SAT2E",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-smzgj0",
              className,
              classNames
            )} framer-2z5001`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "LhN0vuRQJ",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { "LhN0vuRQJ-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-183mk7o",
                    "data-styles-preset": "pU1l54HaN",
                    children: "See all",
                  }),
                }),
                className: "framer-1ipt9kd",
                "data-framer-name": "See all",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "FUfDXfvQV",
                style: { "--framer-paragraph-spacing": "0px", opacity: 1 },
                variants: { "LhN0vuRQJ-hover": { opacity: 0.3 } },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-gt7rgk",
                layoutDependency: layoutDependency,
                layoutId: "Ih2ZV8qKO",
                style: {
                  backgroundColor:
                    "var(--token-29b0dbc5-7e1f-4b3e-8954-a3e1672ca3b5, rgb(198, 241, 157))",
                  borderBottomLeftRadius: 4,
                  borderBottomRightRadius: 4,
                  borderTopLeftRadius: 4,
                  borderTopRightRadius: 4,
                },
                variants: {
                  "LhN0vuRQJ-hover": {
                    backgroundColor: "rgba(198, 241, 157, 0.3)",
                  },
                },
                children: /*#__PURE__*/ _jsx(Vector, {
                  animated: true,
                  className: "framer-x7opmz",
                  layoutDependency: layoutDependency,
                  layoutId: "rTDm6qMIj",
                  style: {
                    "--18xqdng": "rgb(15, 15, 15)",
                    "--x9dcxd": "rgb(15, 31, 16)",
                  },
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-TblLH.framer-2z5001, .framer-TblLH .framer-2z5001 { display: block; }",
  ".framer-TblLH.framer-smzgj0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-TblLH .framer-1ipt9kd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-TblLH .framer-gt7rgk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 26px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 26px; }",
  ".framer-TblLH .framer-x7opmz { flex: none; height: var(--framer-aspect-ratio-supported, 29px); position: relative; width: 111%; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 26
 * @framerIntrinsicWidth 105
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"DT8dovlKY":{"layout":["auto","auto"]}}}
 * @framerVariables {"hhO8Dvlrl":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerevj9SAT2E = withCSS(Component, css, "framer-TblLH");
export default Framerevj9SAT2E;
Framerevj9SAT2E.displayName = "See all blog";
Framerevj9SAT2E.defaultProps = { height: 26, width: 105 };
addPropertyControls(Framerevj9SAT2E, {
  hhO8Dvlrl: { title: "Link", type: ControlType.Link },
});
addFonts(
  Framerevj9SAT2E,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...VectorFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerevj9SAT2E",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"DT8dovlKY":{"layout":["auto","auto"]}}}',
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerVariables: '{"hhO8Dvlrl":"link"}',
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "26",
        framerIntrinsicWidth: "105",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
