// Generated by Framer (a4aa1f7)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = { eE2UIThzs: { hover: true } };
const serializationHash = "framer-lyUyb";
const variantClassNames = { eE2UIThzs: "framer-v-mq09z1" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, title, width, ...props }) => {
  return {
    ...props,
    iQGzIs5UN: title ?? props.iQGzIs5UN ?? "Solutions",
    r7Zwo2wjL: link ?? props.r7Zwo2wjL,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    iQGzIs5UN,
    r7Zwo2wjL,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "eE2UIThzs",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: r7Zwo2wjL,
          motionChild: true,
          nodeId: "eE2UIThzs",
          scopeId: "TsBHhzTZU",
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-mq09z1",
              className,
              classNames
            )} framer-g6e7i6`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "eE2UIThzs",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { "eE2UIThzs-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7R2Vpc3QgTW9uby1yZWd1bGFy",
                    "--framer-font-family": '"Geist Mono", monospace',
                    "--framer-line-height": "120%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(213, 238, 188))",
                    "--framer-text-transform": "uppercase",
                  },
                  children: "Solutions",
                }),
              }),
              className: "framer-zh4fj6",
              "data-framer-name": "Solutions",
              fonts: ["GF;Geist Mono-regular"],
              layoutDependency: layoutDependency,
              layoutId: "I95:799;89:698",
              style: {
                "--extracted-r6o4lv": "rgb(213, 238, 188)",
                "--framer-paragraph-spacing": "0px",
              },
              text: iQGzIs5UN,
              variants: {
                "eE2UIThzs-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255))",
                },
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  "eE2UIThzs-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QgTW9uby1yZWd1bGFy",
                          "--framer-font-family": '"Geist Mono", monospace',
                          "--framer-line-height": "120%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-85221088-9e29-4b0c-9543-d806ed6d5f2c, rgb(255, 255, 255)))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "Solutions",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-lyUyb.framer-g6e7i6, .framer-lyUyb .framer-g6e7i6 { display: block; }",
  ".framer-lyUyb.framer-mq09z1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-lyUyb .framer-zh4fj6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 19
 * @framerIntrinsicWidth 86.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"yM0_XHuUz":{"layout":["auto","auto"]}}}
 * @framerVariables {"iQGzIs5UN":"title","r7Zwo2wjL":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTsBHhzTZU = withCSS(Component, css, "framer-lyUyb");
export default FramerTsBHhzTZU;
FramerTsBHhzTZU.displayName = "Footer Item";
FramerTsBHhzTZU.defaultProps = { height: 19, width: 86.5 };
addPropertyControls(FramerTsBHhzTZU, {
  iQGzIs5UN: {
    defaultValue: "Solutions",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  r7Zwo2wjL: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerTsBHhzTZU,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist Mono",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerTsBHhzTZU",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"yM0_XHuUz":{"layout":["auto","auto"]}}}',
        framerIntrinsicHeight: "19",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "86.5",
        framerVariables: '{"iQGzIs5UN":"title","r7Zwo2wjL":"link"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./TsBHhzTZU.map
