// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/t3xeOFBHgPkHyO22EPW7/fSEo8mzDFu786v6snpfu/P8P5yhthX.js";
import IconsCards from "https://framerusercontent.com/modules/pHoRyk9TTPGfrHupKiv2/ky0tWEJ0k6BnzmrA3w4r/EflXNSDYC.js";
const IconsCardsFonts = getFonts(IconsCards);
const IconsCardsControls = getPropertyControls(IconsCards);
const cycleOrder = ["EP2PDs0Uj", "QmOZFALs3", "kaw8ekdqd"];
const serializationHash = "framer-PYOUp";
const variantClassNames = {
  EP2PDs0Uj: "framer-v-n4gv6j",
  kaw8ekdqd: "framer-v-1jlon6k",
  QmOZFALs3: "framer-v-o6j12j",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = {
  "agr analytics mob": "F1eX7LNl2",
  "agr analytics": "Mannp5RMg",
  "anthena mob": "ZL9ANf0RL",
  "atom mob": "jCB3nSVsD",
  "block mob": "WkiIqulm8",
  "cert check mob": "rHBap8jrh",
  "certificate check": "mqWVnHvDZ",
  "graphic mob": "g0iKdeBoI",
  "square mob": "qUuHQoUo7",
  "stack mob": "LZMx5sWKY",
  "tracked mob": "KtUBSvDDw",
  antena: "W7BNIpRbp",
  atom: "K3n4sE_pW",
  block: "OgYNYdAiU",
  graphic: "qer6PYh8d",
  square: "LG2sqqDSD",
  stack: "PLcA0Z94r",
  tracked: "JYFrpRR62",
};
const humanReadableVariantMap = {
  "small dsk\\": "QmOZFALs3",
  "Variant 1": "EP2PDs0Uj",
  XL: "kaw8ekdqd",
};
const getProps = ({ height, id, text, variant1, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "EP2PDs0Uj",
    wqNntlpHn:
      humanReadableEnumMap[variant1] ??
      variant1 ??
      props.wqNntlpHn ??
      "OgYNYdAiU",
    Y7Al5LpNA:
      text ??
      props.Y7Al5LpNA ??
      "Continuous carbon exchange tracked across ecosystems, in soil, plants, and atmosphere",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    wqNntlpHn,
    Y7Al5LpNA,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "EP2PDs0Uj",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-n4gv6j",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "EP2PDs0Uj",
          ref: refBinding,
          style: {
            backgroundColor: "rgb(245, 244, 242)",
            borderBottomLeftRadius: 24,
            borderBottomRightRadius: 24,
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            ...style,
          },
          ...addPropertyOverrides(
            {
              kaw8ekdqd: { "data-framer-name": "XL" },
              QmOZFALs3: { "data-framer-name": "small dsk\\" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 54,
              y: (componentViewport?.y || 0) + 20 + 0,
              ...addPropertyOverrides(
                { kaw8ekdqd: { y: (componentViewport?.y || 0) + 24 + 0 } },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1ktgpu5-container",
                layoutDependency: layoutDependency,
                layoutId: "CnosfFu_I-container",
                nodeId: "CnosfFu_I",
                rendersWithMotion: true,
                scopeId: "k2b2uc4Il",
                children: /*#__PURE__*/ _jsx(IconsCards, {
                  height: "100%",
                  id: "CnosfFu_I",
                  layoutId: "CnosfFu_I",
                  variant: wqNntlpHn,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-14anx17",
                  "data-styles-preset": "P8P5yhthX",
                  children:
                    "Continuous carbon exchange tracked across ecosystems, in soil, plants, and atmosphere",
                }),
              }),
              className: "framer-9085d4",
              "data-framer-name":
                "Continuous carbon exchange tracked across ecosystems, in soil, plants, and atmosphere",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "n9SZyL8IJ",
              style: { "--framer-paragraph-spacing": "0px" },
              text: Y7Al5LpNA,
              variants: {
                kaw8ekdqd: {
                  "--extracted-r6o4lv":
                    "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                },
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  kaw8ekdqd: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Geist Regular", "Geist Regular Placeholder", sans-serif',
                          "--framer-font-size": "36px",
                          "--framer-letter-spacing": "-0.04em",
                          "--framer-line-height": "100%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16)))",
                        },
                        children:
                          "Continuous carbon exchange tracked across ecosystems, in soil, plants, and atmosphere",
                      }),
                    }),
                    fonts: ["CUSTOM;Geist Regular"],
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-PYOUp.framer-og9w5j, .framer-PYOUp .framer-og9w5j { display: block; }",
  ".framer-PYOUp.framer-n4gv6j { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; width: 379px; }",
  ".framer-PYOUp .framer-1ktgpu5-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-PYOUp .framer-9085d4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-PYOUp.framer-v-1jlon6k.framer-n4gv6j { gap: 32px; padding: 24px; width: 559px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 294
 * @framerIntrinsicWidth 379
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"QmOZFALs3":{"layout":["fixed","auto"]},"kaw8ekdqd":{"layout":["fixed","auto"]}}}
 * @framerVariables {"wqNntlpHn":"variant1","Y7Al5LpNA":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerk2b2uc4Il = withCSS(Component, css, "framer-PYOUp");
export default Framerk2b2uc4Il;
Framerk2b2uc4Il.displayName = "Card Solution Callout";
Framerk2b2uc4Il.defaultProps = { height: 294, width: 379 };
addPropertyControls(Framerk2b2uc4Il, {
  variant: {
    options: ["EP2PDs0Uj", "QmOZFALs3", "kaw8ekdqd"],
    optionTitles: ["Variant 1", "small dsk\\", "XL"],
    title: "Variant",
    type: ControlType.Enum,
  },
  wqNntlpHn: IconsCardsControls?.["variant"] && {
    ...IconsCardsControls["variant"],
    defaultValue: "OgYNYdAiU",
    description: undefined,
    hidden: undefined,
    title: "Variant",
  },
  Y7Al5LpNA: {
    defaultValue:
      "Continuous carbon exchange tracked across ecosystems, in soil, plants, and atmosphere",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
});
addFonts(
  Framerk2b2uc4Il,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          family: "Geist Regular",
          source: "custom",
          url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
        },
      ],
    },
    ...IconsCardsFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerk2b2uc4Il",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "294",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "379",
        framerVariables: '{"wqNntlpHn":"variant1","Y7Al5LpNA":"text"}',
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"QmOZFALs3":{"layout":["fixed","auto"]},"kaw8ekdqd":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./k2b2uc4Il.map
