// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  SVG,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["tXjUZFzos", "SlUzYERA7"];
const serializationHash = "framer-7bzBz";
const variantClassNames = {
  SlUzYERA7: "framer-v-1wvnf91",
  tXjUZFzos: "framer-v-o77jvu",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Dark: "SlUzYERA7", Light: "tXjUZFzos" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "tXjUZFzos",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "tXjUZFzos",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "SlUzYERA7") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "SlUzYERA7") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-o77jvu",
            className,
            classNames
          ),
          "data-framer-name": "Light",
          layoutDependency: layoutDependency,
          layoutId: "tXjUZFzos",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { SlUzYERA7: { "data-framer-name": "Dark" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-6rplq8",
                "data-framer-name": "Light",
                fill: "rgba(0,0,0,1)",
                intrinsicHeight: 7,
                intrinsicWidth: 10,
                layoutDependency: layoutDependency,
                layoutId: "I68:1388;11:363",
                svg: '<svg width="10" height="7" viewBox="-1 -1 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M7.5 0.75L4 4.25L0.5 0.75" stroke="white" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n',
                withExternalLayout: true,
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-bzij3w",
                "data-framer-name": "Dark",
                fill: "rgba(0,0,0,1)",
                intrinsicHeight: 7,
                intrinsicWidth: 10,
                layoutDependency: layoutDependency,
                layoutId: "I68:1389;45:2144",
                svg: '<svg width="10" height="7" viewBox="-1 -1 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M7.5 0.75L4 4.25L0.5 0.75" stroke="#0F1F10" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n',
                withExternalLayout: true,
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-7bzBz.framer-1c35r16, .framer-7bzBz .framer-1c35r16 { display: block; }",
  ".framer-7bzBz.framer-o77jvu { height: 7px; overflow: visible; position: relative; width: 10px; }",
  ".framer-7bzBz .framer-6rplq8, .framer-7bzBz .framer-bzij3w { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(42.857142857142875% - 100% / 2); width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 7
 * @framerIntrinsicWidth 10
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"SlUzYERA7":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerEn5UF98oR = withCSS(Component, css, "framer-7bzBz");
export default FramerEn5UF98oR;
FramerEn5UF98oR.displayName = "Drop Arrow";
FramerEn5UF98oR.defaultProps = { height: 7, width: 10 };
addPropertyControls(FramerEn5UF98oR, {
  variant: {
    options: ["tXjUZFzos", "SlUzYERA7"],
    optionTitles: ["Light", "Dark"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerEn5UF98oR, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerEn5UF98oR",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "7",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"SlUzYERA7":{"layout":["fixed","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerIntrinsicWidth: "10",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./En5UF98oR.map
