// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  PropertyOverrides,
  RichText,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useRouteElementId,
  useSiteRefs,
  withCSS,
} from "framer";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Lenis from "https://framerusercontent.com/modules/bSeEZJm22jsjERCOGQvq/VB8afRw6VQVsqyyipLnz/Lenis.js";
import BadgeTitle from "#framer/local/canvasComponent/m8mchcvpq/m8mchcvpq.js";
import * as sharedStyle3 from "#framer/local/css/AouQgd1gR/AouQgd1gR.js";
import * as sharedStyle2 from "#framer/local/css/BV9aesefd/BV9aesefd.js";
import * as sharedStyle1 from "#framer/local/css/IOQroGfcd/IOQroGfcd.js";
import * as sharedStyle from "#framer/local/css/lxwtqyXJR/lxwtqyXJR.js";
import metadataProvider from "#framer/local/webPageMetadata/JRm9rV5Ry/JRm9rV5Ry.js";
const LenisFonts = getFonts(Lenis);
const BadgeTitleFonts = getFonts(BadgeTitle);
const breakpoints = {
  GYkZXP59Z: "(min-width: 1920px) and (max-width: 2559px)",
  HMALJKqtR: "(max-width: 959px)",
  m2j2YcUK3: "(min-width: 1440px) and (max-width: 1919px)",
  PT9l1BoZ1: "(min-width: 2560px)",
  x9QpVrYPJ: "(min-width: 960px) and (max-width: 1439px)",
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-GcNB7";
const variantClassNames = {
  GYkZXP59Z: "framer-v-abr48g",
  HMALJKqtR: "framer-v-17jei31",
  m2j2YcUK3: "framer-v-g3ffrs",
  PT9l1BoZ1: "framer-v-1bua42m",
  x9QpVrYPJ: "framer-v-1qfmupm",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const humanReadableVariantMap = {
  "Small DSK": "x9QpVrYPJ",
  Desktop: "m2j2YcUK3",
  L: "GYkZXP59Z",
  Phone: "HMALJKqtR",
  XL: "PT9l1BoZ1",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "m2j2YcUK3",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider(undefined, activeLocale),
    [undefined, activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const elementId = useRouteElementId("CGLnaFkZx");
  const dynamicRef = useSiteRefs();
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: { primaryVariantId: "m2j2YcUK3", variantClassNames },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-95995eb5-c56a-4901-8fd5-d6ed3e73179d, rgb(15, 15, 15)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-g3ffrs", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(Container, {
                className: "framer-2qbijc-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                nodeId: "qo0JU3JtH",
                scopeId: "JRm9rV5Ry",
                children: /*#__PURE__*/ _jsx(Lenis, {
                  height: "100%",
                  id: "qo0JU3JtH",
                  infinite: false,
                  intensity: 12,
                  layoutId: "qo0JU3JtH",
                  orientation: "vertical",
                  smooth: true,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs("div", {
              className: "framer-df9lnm",
              "data-framer-name": "Hero",
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-rr9iyq",
                  "data-framer-name": "L",
                  children: [
                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        HMALJKqtR: {
                          y:
                            (componentViewport?.y || 0) +
                            0 +
                            200 +
                            141 +
                            0 +
                            0 +
                            0,
                        },
                      },
                      children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 24,
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          200 +
                          169 +
                          0 +
                          0 +
                          0,
                        children: /*#__PURE__*/ _jsx(Container, {
                          className: "framer-1m406f3-container",
                          nodeId: "HdDdiaPHV",
                          scopeId: "JRm9rV5Ry",
                          children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                              GYkZXP59Z: { variant: "C1EP2UB30" },
                              PT9l1BoZ1: { variant: "C1EP2UB30" },
                            },
                            children: /*#__PURE__*/ _jsx(BadgeTitle, {
                              gcVlh98w5: "Terms of use",
                              height: "100%",
                              id: "HdDdiaPHV",
                              layoutId: "HdDdiaPHV",
                              variant: "xdy29zwVa",
                              width: "100%",
                            }),
                          }),
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx("h1", {
                          className: "framer-styles-preset-1schlan",
                          "data-styles-preset": "lxwtqyXJR",
                          children: "‍Thank you for visiting prakriti.earth",
                        }),
                      }),
                      className: "framer-1qdfv0n",
                      "data-framer-name": "Prakriti in the News",
                      fonts: ["Inter"],
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-ynpchi",
                  "data-framer-name": "IMG_Container",
                  children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      GYkZXP59Z: {
                        background: {
                          alt: "grass-covered field",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              200 +
                              169 +
                              246 +
                              0
                          ),
                          pixelHeight: 651,
                          pixelWidth: 1384,
                          sizes: `max(${
                            componentViewport?.width || "100vw"
                          } - 56px, 1px)`,
                          src: "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png",
                          srcSet:
                            "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=512 512w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png 1384w",
                        },
                      },
                      HMALJKqtR: {
                        background: {
                          alt: "grass-covered field",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              200 +
                              141 +
                              214 +
                              0
                          ),
                          pixelHeight: 651,
                          pixelWidth: 1384,
                          sizes: `max(${
                            componentViewport?.width || "100vw"
                          } - 32px, 1px)`,
                          src: "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png",
                          srcSet:
                            "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=512 512w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png 1384w",
                        },
                      },
                      PT9l1BoZ1: {
                        background: {
                          alt: "grass-covered field",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              200 +
                              169 +
                              246 +
                              0
                          ),
                          pixelHeight: 651,
                          pixelWidth: 1384,
                          sizes: `max(${
                            componentViewport?.width || "100vw"
                          } - 56px, 1px)`,
                          src: "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png",
                          srcSet:
                            "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=512 512w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png 1384w",
                        },
                      },
                    },
                    children: /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "grass-covered field",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 0 + 200 + 169 + 222 + 0
                        ),
                        pixelHeight: 651,
                        pixelWidth: 1384,
                        sizes: `max(${
                          componentViewport?.width || "100vw"
                        } - 56px, 1px)`,
                        src: "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png",
                        srcSet:
                          "https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=512 512w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/dARRRZSooP95h3BiWCT9BJr9eg.png 1384w",
                      },
                      className: "framer-1ytyg01",
                      "data-framer-name": "visualelectric-1749132611400 1",
                      id: elementId,
                      ref: dynamicRef(elementId),
                    }),
                  }),
                }),
              ],
            }),
            /*#__PURE__*/ _jsxs("div", {
              className: "framer-1bitwac",
              "data-framer-name": "Content",
              children: [
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-9l4bnj",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx("p", {
                        className: "framer-styles-preset-7ilx2o",
                        "data-styles-preset": "IOQroGfcd",
                        children: "Effective Date: [Date]",
                      }),
                    }),
                    className: "framer-stdngk",
                    "data-framer-name": "Effective Date: [Date]",
                    fonts: ["Inter"],
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-1ci5x0s",
                  "data-framer-name": "Frame 1000005796",
                  children: [
                    /*#__PURE__*/ _jsx("div", {
                      className: "framer-1srst4b",
                      "data-framer-name": "Component_Paragraph",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx("h5", {
                            className: "framer-styles-preset-s7akgw",
                            "data-styles-preset": "BV9aesefd",
                            children:
                              "These Terms of Use (“Terms”) govern your access to and use of www.prakriti.earth (the “Site”), operated by Prakriti (“we,” “our,” or “us”). By accessing or using this Site, you acknowledge that you have read, understood, and agreed to be bound by these Terms. If you do not agree with any part of these Terms, please do not use the Site.",
                          }),
                        }),
                        className: "framer-4i2o13",
                        "data-framer-name":
                          "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                        fonts: ["Inter"],
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-10l10w",
                      "data-framer-name": "Frame 1000004770",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "1. Use of the Site",
                            }),
                          }),
                          className: "framer-1u1svgx",
                          "data-framer-name": "‍1. Information We Collect",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-dtgf0z",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                              HMALJKqtR: {
                                children: /*#__PURE__*/ _jsxs(React.Fragment, {
                                  children: [
                                    /*#__PURE__*/ _jsx("p", {
                                      className: "framer-styles-preset-x7odja",
                                      "data-styles-preset": "AouQgd1gR",
                                      children:
                                        "You agree to use the Site only for lawful purposes and in accordance with these Terms. Specifically, you agree not to:\u2028\u2028",
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                      className: "framer-styles-preset-x7odja",
                                      "data-styles-preset": "AouQgd1gR",
                                      children: /*#__PURE__*/ _jsx("br", {
                                        className: "trailing-break",
                                      }),
                                    }),
                                    /*#__PURE__*/ _jsxs("ul", {
                                      className: "framer-styles-preset-x7odja",
                                      "data-styles-preset": "AouQgd1gR",
                                      children: [
                                        /*#__PURE__*/ _jsx("li", {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            children:
                                              "Violate any applicable laws or regulations.",
                                          }),
                                        }),
                                        /*#__PURE__*/ _jsx("li", {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            children:
                                              "Access or attempt to access unauthorized areas of the Site or our systems.",
                                          }),
                                        }),
                                        /*#__PURE__*/ _jsx("li", {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            children:
                                              "Interfere with the functionality, security, or performance of the Site or its underlying infrastructure.",
                                          }),
                                        }),
                                      ],
                                    }),
                                  ],
                                }),
                                fonts: ["Inter"],
                              },
                            },
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsxs(React.Fragment, {
                                children: [
                                  /*#__PURE__*/ _jsx("p", {
                                    style: {
                                      "--font-selector":
                                        "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Geist Regular", "Geist Regular Placeholder", sans-serif',
                                      "--framer-font-size": "18px",
                                      "--framer-letter-spacing": "-0.02em",
                                      "--framer-line-height": "120%",
                                      "--framer-text-color":
                                        "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                                    },
                                    children:
                                      "You agree to use the Site only for lawful purposes and in accordance with these Terms. Specifically, you agree not to:\u2028\u2028",
                                  }),
                                  /*#__PURE__*/ _jsx("p", {
                                    style: {
                                      "--font-selector":
                                        "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Geist Regular", "Geist Regular Placeholder", sans-serif',
                                      "--framer-font-size": "18px",
                                      "--framer-letter-spacing": "-0.02em",
                                      "--framer-line-height": "120%",
                                      "--framer-text-color":
                                        "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                                    },
                                    children: /*#__PURE__*/ _jsx("br", {
                                      className: "trailing-break",
                                    }),
                                  }),
                                  /*#__PURE__*/ _jsxs("ul", {
                                    style: {
                                      "--font-selector":
                                        "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
                                      "--framer-font-family":
                                        '"Geist Regular", "Geist Regular Placeholder", sans-serif',
                                      "--framer-font-size": "18px",
                                      "--framer-letter-spacing": "-0.02em",
                                      "--framer-line-height": "120%",
                                      "--framer-text-color":
                                        "var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, rgb(15, 31, 16))",
                                    },
                                    children: [
                                      /*#__PURE__*/ _jsx("li", {
                                        children: /*#__PURE__*/ _jsx("p", {
                                          children:
                                            "Violate any applicable laws or regulations.",
                                        }),
                                      }),
                                      /*#__PURE__*/ _jsx("li", {
                                        children: /*#__PURE__*/ _jsx("p", {
                                          children:
                                            "Access or attempt to access unauthorized areas of the Site or our systems.",
                                        }),
                                      }),
                                      /*#__PURE__*/ _jsx("li", {
                                        children: /*#__PURE__*/ _jsx("p", {
                                          children:
                                            "Interfere with the functionality, security, or performance of the Site or its underlying infrastructure.",
                                        }),
                                      }),
                                    ],
                                  }),
                                ],
                              }),
                              className: "framer-1mdr63e",
                              "data-framer-name":
                                "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                              fonts: ["CUSTOM;Geist Regular"],
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-pkq9oa",
                      "data-framer-name": "Frame 1000004774",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "2. Intellectual Property",
                            }),
                          }),
                          className: "framer-93rk6e",
                          "data-framer-name": "‍2. How We Use Your Information",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-x8fwp0",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "All content on the Site—including but not limited to text, graphics, images, logos, and code—is the property of Prakriti or its content providers and is protected by intellectual property laws. You may not copy, reproduce, distribute, modify, or create derivative works from any content without prior written permission from Prakriti.",
                              }),
                            }),
                            className: "framer-10ew666",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-1hdj3by",
                      "data-framer-name": "Frame 1000004775",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "3. Disclaimers",
                            }),
                          }),
                          className: "framer-k0ua9q",
                          "data-framer-name":
                            "‍3. Cookies and Similar Technologies",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-vjg2lb",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "The Site is provided on an “as is” and “as available” basis without any warranties, express or implied. We do not warrant that the Site will be uninterrupted, error-free, or secure. Your use of the Site is at your own risk.",
                              }),
                            }),
                            className: "framer-2vbzf9",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-ags665",
                      "data-framer-name": "Frame 1000004776",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "4. Limitation of Liability",
                            }),
                          }),
                          className: "framer-w3sreo",
                          "data-framer-name": "‍4. Third-Party Disclosure",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-1i9k5q4",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "To the fullest extent permitted by law, Prakriti shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of or relating to your use of (or inability to use) the Site.",
                              }),
                            }),
                            className: "framer-1dalild",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-10qm6sz",
                      "data-framer-name": "Frame 1000004777",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "5. Third-Party Links",
                            }),
                          }),
                          className: "framer-ywhmjn",
                          "data-framer-name": "‍5. Data Transfers",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-1w75pje",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "‍As a global website, we may transfer your personal information to countries outside the European Economic Area (EEA) or Switzerland, which may have different data protection laws. In such cases, we will ensure that adequate safeguards are in place to protect your data, such as Standard Contractual Clauses approved by the European Commission.",
                              }),
                            }),
                            className: "framer-8s1ouu",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-15an84",
                      "data-framer-name": "Frame 1000004778",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "6. Changes to These Terms",
                            }),
                          }),
                          className: "framer-1g7tsd9",
                          "data-framer-name": "‍6. Data Security",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-fpqn4w",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "‍We take appropriate technical and organizational measures to protect the security of your personal information and prevent unauthorized access, disclosure, or alteration. However, no method of transmission over the internet or electronic storage is entirely secure, and we cannot guarantee absolute security.",
                              }),
                            }),
                            className: "framer-12p7p01",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-1mus9kz",
                          "data-framer-name": "Component_Paragraph",
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-1pggxzp",
                      "data-framer-name": "Frame 1000004779",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "7. Governing Law",
                            }),
                          }),
                          className: "framer-1t154db",
                          "data-framer-name": "‍7. Children's Privacy",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-1mr15m5",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-x7odja",
                                "data-styles-preset": "AouQgd1gR",
                                children:
                                  "‍Our Website is not intended for individuals under the age of 16. We do not knowingly collect personal information from children under this age. If we become aware that we have inadvertently collected personal information from a child, we will take steps to delete the information as soon as possible.",
                              }),
                            }),
                            className: "framer-x175lx",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-f1wzzr",
                      "data-framer-name": "Frame 1000004781",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h5", {
                              className: "framer-styles-preset-s7akgw",
                              "data-styles-preset": "BV9aesefd",
                              children: "‍8. Contact Us",
                            }),
                          }),
                          className: "framer-186o80s",
                          "data-framer-name": "‍9. Contact Us",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-fmy5dn",
                          "data-framer-name": "Component_Paragraph",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsxs(React.Fragment, {
                              children: [
                                /*#__PURE__*/ _jsx("p", {
                                  className: "framer-styles-preset-x7odja",
                                  "data-styles-preset": "AouQgd1gR",
                                  children:
                                    "If you have any questions or concerns about these Terms, please contact us at:\u2028\u2028",
                                }),
                                /*#__PURE__*/ _jsx("p", {
                                  className: "framer-styles-preset-x7odja",
                                  "data-styles-preset": "AouQgd1gR",
                                  children:
                                    "Email: contact@prakriti.earth \u2028\u2028",
                                }),
                                /*#__PURE__*/ _jsx("p", {
                                  className: "framer-styles-preset-x7odja",
                                  "data-styles-preset": "AouQgd1gR",
                                  children:
                                    "Addresses: New Delhi - Bengaluru, India\u2028\u2028",
                                }),
                              ],
                            }),
                            className: "framer-197u9i3",
                            "data-framer-name":
                              "Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor.Fusce vehicula dolor arcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor. rcu, sit amet blandit dolor mollis nec. Fusce vehicula dolor arcu, sit amet blandit dolor",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-GcNB7.framer-2opxwh, .framer-GcNB7 .framer-2opxwh { display: block; }",
  ".framer-GcNB7.framer-g3ffrs { align-content: center; align-items: center; background-color: var(--token-95995eb5-c56a-4901-8fd5-d6ed3e73179d, #0f0f0f); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 1000px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
  ".framer-GcNB7 .framer-2qbijc-container, .framer-GcNB7 .framer-1m406f3-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-GcNB7 .framer-df9lnm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: center; overflow: hidden; padding: 169px 28px 28px 28px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-rr9iyq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-1qdfv0n { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 664px; word-break: break-word; word-wrap: break-word; }",
  ".framer-GcNB7 .framer-ynpchi { align-content: center; align-items: center; aspect-ratio: 2.1259600614439322 / 1; border-bottom-left-radius: 24px; border-bottom-right-radius: 24px; border-top-left-radius: 24px; border-top-right-radius: 24px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 651px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-GcNB7 .framer-1ytyg01 { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
  ".framer-GcNB7 .framer-1bitwac { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: center; overflow: hidden; padding: 41px 28px 148px 28px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-9l4bnj { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-GcNB7 .framer-stdngk { --framer-paragraph-spacing: 0px; flex: 1 0 0px; height: auto; opacity: 0.7; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-GcNB7 .framer-1ci5x0s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 58%; }",
  ".framer-GcNB7 .framer-1srst4b, .framer-GcNB7 .framer-dtgf0z, .framer-GcNB7 .framer-x8fwp0, .framer-GcNB7 .framer-vjg2lb, .framer-GcNB7 .framer-1i9k5q4, .framer-GcNB7 .framer-1w75pje, .framer-GcNB7 .framer-fpqn4w, .framer-GcNB7 .framer-1mr15m5, .framer-GcNB7 .framer-fmy5dn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-4i2o13, .framer-GcNB7 .framer-1mdr63e, .framer-GcNB7 .framer-10ew666, .framer-GcNB7 .framer-2vbzf9, .framer-GcNB7 .framer-1dalild, .framer-GcNB7 .framer-8s1ouu, .framer-GcNB7 .framer-12p7p01, .framer-GcNB7 .framer-x175lx, .framer-GcNB7 .framer-197u9i3 { --framer-paragraph-spacing: 0px; flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-GcNB7 .framer-10l10w, .framer-GcNB7 .framer-pkq9oa, .framer-GcNB7 .framer-1hdj3by, .framer-GcNB7 .framer-ags665, .framer-GcNB7 .framer-10qm6sz, .framer-GcNB7 .framer-1pggxzp, .framer-GcNB7 .framer-f1wzzr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-1u1svgx, .framer-GcNB7 .framer-93rk6e, .framer-GcNB7 .framer-k0ua9q, .framer-GcNB7 .framer-w3sreo, .framer-GcNB7 .framer-ywhmjn, .framer-GcNB7 .framer-1g7tsd9, .framer-GcNB7 .framer-1t154db, .framer-GcNB7 .framer-186o80s { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-GcNB7 .framer-15an84 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 152px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-GcNB7 .framer-1mus9kz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; min-height: 168px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  "@media (min-width: 960px) and (max-width: 1439px) { .framer-GcNB7.framer-g3ffrs { height: 4166px; width: 960px; } .framer-GcNB7 .framer-ynpchi { height: var(--framer-aspect-ratio-supported, 425px); }}",
  "@media (max-width: 959px) { .framer-GcNB7.framer-g3ffrs { height: 4166px; width: 390px; } .framer-GcNB7 .framer-df9lnm { padding: 141px 16px 28px 16px; } .framer-GcNB7 .framer-rr9iyq { gap: 48px; } .framer-GcNB7 .framer-1qdfv0n, .framer-GcNB7 .framer-1ci5x0s { width: 100%; } .framer-GcNB7 .framer-ynpchi { height: var(--framer-aspect-ratio-supported, 169px); } .framer-GcNB7 .framer-1bitwac { flex-direction: column; padding: 41px 16px 120px 16px; } .framer-GcNB7 .framer-9l4bnj { flex: none; width: 100%; }}",
  "@media (min-width: 2560px) { .framer-GcNB7.framer-g3ffrs { height: 5791px; width: 2560px; } .framer-GcNB7 .framer-rr9iyq { gap: 80px; } .framer-GcNB7 .framer-1qdfv0n { width: 1104px; } .framer-GcNB7 .framer-ynpchi { height: var(--framer-aspect-ratio-supported, 1178px); } .framer-GcNB7 .framer-1bitwac { padding: 41px 28px 200px 28px; }}",
  "@media (min-width: 1920px) and (max-width: 2559px) { .framer-GcNB7.framer-g3ffrs { height: 4838px; width: 1920px; } .framer-GcNB7 .framer-rr9iyq { gap: 80px; } .framer-GcNB7 .framer-1qdfv0n { width: 1104px; } .framer-GcNB7 .framer-ynpchi { height: var(--framer-aspect-ratio-supported, 877px); } .framer-GcNB7 .framer-1bitwac { padding: 41px 28px 200px 28px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 4677.5
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"x9QpVrYPJ":{"layout":["fixed","fixed"]},"HMALJKqtR":{"layout":["fixed","fixed"]},"PT9l1BoZ1":{"layout":["fixed","fixed"]},"GYkZXP59Z":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"CGLnaFkZx":{"pattern":":CGLnaFkZx","name":"nav-swap"}}
 * @framerResponsiveScreen
 */ const FramerJRm9rV5Ry = withCSS(Component, css, "framer-GcNB7");
export default FramerJRm9rV5Ry;
FramerJRm9rV5Ry.displayName = "Privacy Policy";
FramerJRm9rV5Ry.defaultProps = { height: 4677.5, width: 1440 };
addFonts(
  FramerJRm9rV5Ry,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          family: "Geist Regular",
          source: "custom",
          url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
        },
      ],
    },
    ...LenisFonts,
    ...BadgeTitleFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerJRm9rV5Ry",
      slots: [],
      annotations: {
        framerScrollSections:
          '{"CGLnaFkZx":{"pattern":":CGLnaFkZx","name":"nav-swap"}}',
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1440",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"x9QpVrYPJ":{"layout":["fixed","fixed"]},"HMALJKqtR":{"layout":["fixed","fixed"]},"PT9l1BoZ1":{"layout":["fixed","fixed"]},"GYkZXP59Z":{"layout":["fixed","fixed"]}}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerAcceptsLayoutTemplate: "true",
        framerIntrinsicHeight: "4677.5",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerResponsiveScreen: "",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
