// Generated by Framer (64bdc4e)
import { fontStore } from "framer";
fontStore.loadFonts(["GF;Geist Mono-500", "GF;Geist Mono-700"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Geist Mono",
        openType: true,
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
        weight: "500",
      },
      {
        family: "Geist Mono",
        openType: true,
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHaL55W7ihaO_CS.woff2",
        weight: "700",
      },
    ],
  },
];
export const css = [
  ".framer-2xsuc .framer-styles-preset-1cvb0w0:not(.rich-text-wrapper), .framer-2xsuc .framer-styles-preset-1cvb0w0.rich-text-wrapper p { --framer-font-family: \"Geist Mono\", monospace; --framer-font-family-bold: \"Geist Mono\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on, 'ss04' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }",
  "@media (max-width: 1439px) and (min-width: 1200px) { .framer-2xsuc .framer-styles-preset-1cvb0w0:not(.rich-text-wrapper), .framer-2xsuc .framer-styles-preset-1cvb0w0.rich-text-wrapper p { --framer-font-family: \"Geist Mono\", monospace; --framer-font-family-bold: \"Geist Mono\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on, 'ss04' on; --framer-font-size: 11px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
  "@media (max-width: 1199px) and (min-width: 960px) { .framer-2xsuc .framer-styles-preset-1cvb0w0:not(.rich-text-wrapper), .framer-2xsuc .framer-styles-preset-1cvb0w0.rich-text-wrapper p { --framer-font-family: \"Geist Mono\", monospace; --framer-font-family-bold: \"Geist Mono\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on, 'ss04' on; --framer-font-size: 9px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 90%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
  "@media (max-width: 959px) and (min-width: 0px) { .framer-2xsuc .framer-styles-preset-1cvb0w0:not(.rich-text-wrapper), .framer-2xsuc .framer-styles-preset-1cvb0w0.rich-text-wrapper p { --framer-font-family: \"Geist Mono\", monospace; --framer-font-family-bold: \"Geist Mono\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on, 'ss04' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-89eb458f-c22d-4db9-991d-dedbff9f9de0, #0f1f10); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
];
export const className = "framer-2xsuc";
export const __FramerMetadata__ = {
  exports: {
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
