// Generated by Framer (7587b09)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const serializationHash = "framer-LabZi";
const variantClassNames = { xUwilAkNd: "framer-v-n18vr4" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "xUwilAkNd",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-n18vr4",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "xUwilAkNd",
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(Image, {
            background: {
              alt: "",
              fit: "fill",
              intrinsicHeight: 264,
              intrinsicWidth: 327,
              loading: getLoadingLazyAtYPosition(
                (componentViewport?.y || 0) +
                  (0 + ((componentViewport?.height || 200) - 0 - 264) / 2)
              ),
              pixelHeight: 528,
              pixelWidth: 654,
              sizes: `calc(${componentViewport?.width || "100vw"} * 0.85)`,
              src: "https://framerusercontent.com/images/SdGIx7vY0Jdod0Rxccv40AXoqM.png?width=654&height=528",
              srcSet:
                "https://framerusercontent.com/images/SdGIx7vY0Jdod0Rxccv40AXoqM.png?scale-down-to=512&width=654&height=528 512w,https://framerusercontent.com/images/SdGIx7vY0Jdod0Rxccv40AXoqM.png?width=654&height=528 654w",
            },
            className: "framer-c010ej",
            "data-framer-name": "Roca front",
            layoutDependency: layoutDependency,
            layoutId: "uNGucHmzO",
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-LabZi.framer-1gao9b3, .framer-LabZi .framer-1gao9b3 { display: block; }",
  ".framer-LabZi.framer-n18vr4 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 200px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 200px; }",
  ".framer-LabZi .framer-c010ej { aspect-ratio: 1.2386363636363635 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 137px); overflow: visible; position: relative; width: 85%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerN6abqcJcm = withCSS(Component, css, "framer-LabZi");
export default FramerN6abqcJcm;
FramerN6abqcJcm.displayName = "Rock 2";
FramerN6abqcJcm.defaultProps = { height: 200, width: 200 };
addFonts(FramerN6abqcJcm, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerN6abqcJcm",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "200",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "200",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./N6abqcJcm.map
