// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  SVG,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/w37zXVgWZy9dkr8JU3N6/ZnpP1vnrSwioiJNyWCgS/BV9aesefd.js";
const cycleOrder = ["HDeldSjQW", "hg1RWCZMo", "DXEeIkdb5"];
const serializationHash = "framer-Ccg6v";
const variantClassNames = {
  DXEeIkdb5: "framer-v-19zmxot",
  HDeldSjQW: "framer-v-18jycd4",
  hg1RWCZMo: "framer-v-1y3nixa",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "HDeldSjQW",
  mob: "hg1RWCZMo",
  XL: "DXEeIkdb5",
};
const getProps = ({ fill, height, id, text, width, ...props }) => {
  return {
    ...props,
    hXET5UbuY:
      text ??
      props.hXET5UbuY ??
      "Supports verified action beyond internal scope",
    SYYtyjMgH: fill ?? props.SYYtyjMgH ?? "rgb(245, 244, 242)",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "HDeldSjQW",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    hXET5UbuY,
    SYYtyjMgH,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "HDeldSjQW",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-18jycd4",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "HDeldSjQW",
          ref: refBinding,
          style: {
            backgroundColor: SYYtyjMgH,
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            ...style,
          },
          variants: {
            DXEeIkdb5: {
              borderBottomLeftRadius: 32,
              borderBottomRightRadius: 32,
              borderTopLeftRadius: 32,
              borderTopRightRadius: 32,
            },
            hg1RWCZMo: {
              borderBottomLeftRadius: 12,
              borderBottomRightRadius: 12,
              borderTopLeftRadius: 12,
              borderTopRightRadius: 12,
            },
          },
          ...addPropertyOverrides(
            {
              DXEeIkdb5: { "data-framer-name": "XL" },
              hg1RWCZMo: { "data-framer-name": "mob" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1ekg5nc",
              "data-framer-name": "Badge",
              layoutDependency: layoutDependency,
              layoutId: "fRyGr99cT",
              style: {
                backgroundColor:
                  "var(--token-29b0dbc5-7e1f-4b3e-8954-a3e1672ca3b5, rgb(198, 241, 157))",
                borderBottomLeftRadius: 99,
                borderBottomRightRadius: 99,
                borderTopLeftRadius: 99,
                borderTopRightRadius: 99,
              },
              children: /*#__PURE__*/ _jsx(SVG, {
                className: "framer-zf5l80",
                "data-framer-name": "Group 1000002642",
                layout: "position",
                layoutDependency: layoutDependency,
                layoutId: "NM1nVCuBc",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 55 55"><path d="M 34.293 21.793 C 34.683 21.402 35.316 21.402 35.707 21.793 C 36.097 22.183 36.097 22.816 35.707 23.207 L 24.707 34.207 C 24.316 34.597 23.683 34.597 23.293 34.207 L 18.293 29.207 C 17.902 28.816 17.902 28.183 18.293 27.793 C 18.659 27.427 19.238 27.404 19.631 27.724 L 19.707 27.793 L 24 32.086 Z" fill="rgb(15,31,16)"></path></svg>',
                svgContentId: 9267576989,
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h5, {
                  className: "framer-styles-preset-s7akgw",
                  "data-styles-preset": "BV9aesefd",
                  children: "Supports verified action beyond internal scope",
                }),
              }),
              className: "framer-friuvj",
              "data-framer-name":
                "Supports verified action beyond internal scope",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "nnbiCizpl",
              style: { "--framer-paragraph-spacing": "0px" },
              text: hXET5UbuY,
              variants: {
                DXEeIkdb5: { "--extracted-1lwpl3i": "rgb(51, 51, 51)" },
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  DXEeIkdb5: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.h5, {
                        style: {
                          "--font-selector": "R0Y7R2Vpc3QtNjAw",
                          "--framer-font-family":
                            '"Geist", "Geist Placeholder", sans-serif',
                          "--framer-font-size": "56px",
                          "--framer-font-weight": "600",
                          "--framer-letter-spacing": "-0.02em",
                          "--framer-line-height": "95%",
                          "--framer-text-color":
                            "var(--extracted-1lwpl3i, rgb(51, 51, 51))",
                        },
                        children:
                          "Supports verified action beyond internal scope",
                      }),
                    }),
                    fonts: ["GF;Geist-600"],
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Ccg6v.framer-z4dmq4, .framer-Ccg6v .framer-z4dmq4 { display: block; }",
  ".framer-Ccg6v.framer-18jycd4 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 434px; justify-content: space-between; overflow: visible; padding: 26px; position: relative; width: 448px; }",
  ".framer-Ccg6v .framer-1ekg5nc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 55px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 55px; }",
  ".framer-Ccg6v .framer-zf5l80 { flex: none; height: 55px; position: relative; width: 55px; }",
  ".framer-Ccg6v .framer-friuvj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-Ccg6v.framer-v-1y3nixa.framer-18jycd4 { padding: 20px; }",
  ".framer-Ccg6v.framer-v-19zmxot.framer-18jycd4 { aspect-ratio: 1.3166869671132766 / 1; height: var(--framer-aspect-ratio-supported, 821px); width: 1081px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 434
 * @framerIntrinsicWidth 448
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"hg1RWCZMo":{"layout":["fixed","fixed"]},"DXEeIkdb5":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"hXET5UbuY":"text","SYYtyjMgH":"fill"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameraokAitGEs = withCSS(Component, css, "framer-Ccg6v");
export default FrameraokAitGEs;
FrameraokAitGEs.displayName = "Card_solutions";
FrameraokAitGEs.defaultProps = { height: 434, width: 448 };
addPropertyControls(FrameraokAitGEs, {
  variant: {
    options: ["HDeldSjQW", "hg1RWCZMo", "DXEeIkdb5"],
    optionTitles: ["Variant 1", "mob", "XL"],
    title: "Variant",
    type: ControlType.Enum,
  },
  hXET5UbuY: {
    defaultValue: "Supports verified action beyond internal scope",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  SYYtyjMgH: {
    defaultValue: "rgb(245, 244, 242)",
    title: "Fill",
    type: ControlType.Color,
  },
});
addFonts(
  FrameraokAitGEs,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          family: "Geist",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RQuQ4mJPby1QNtA.woff2",
          weight: "600",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameraokAitGEs",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerVariables: '{"hXET5UbuY":"text","SYYtyjMgH":"fill"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"hg1RWCZMo":{"layout":["fixed","fixed"]},"DXEeIkdb5":{"layout":["fixed","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "434",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "448",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
