// Generated by Framer (ef9cd67)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Triangle from "https://framerusercontent.com/modules/j19Vg9LeLnxO9nEWWjSJ/NiloZ38FeOu85rlReTVk/CAPKspRPB.js";
const TriangleFonts = getFonts(Triangle);
const TriangleWithFX = withFX(Triangle);
const cycleOrder = ["x1E8Vbms3", "IJ7G7VnMj"];
const serializationHash = "framer-ig5fv";
const variantClassNames = {
  IJ7G7VnMj: "framer-v-owzslc",
  x1E8Vbms3: "framer-v-rquy2o",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 6,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Anim: "IJ7G7VnMj", Static: "x1E8Vbms3" };
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "x1E8Vbms3",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "x1E8Vbms3",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-rquy2o",
            className,
            classNames
          ),
          "data-framer-name": "Static",
          layoutDependency: layoutDependency,
          layoutId: "x1E8Vbms3",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { IJ7G7VnMj: { "data-framer-name": "Anim" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(TriangleWithFX, {
            animated: true,
            className: "framer-1ngm8mn",
            layoutDependency: layoutDependency,
            layoutId: "yORcpGjCI",
            ...addPropertyOverrides(
              {
                IJ7G7VnMj: {
                  __framer__loop: animation,
                  __framer__loopEffectEnabled: true,
                  __framer__loopPauseOffscreen: true,
                  __framer__loopRepeatDelay: 0,
                  __framer__loopRepeatType: "loop",
                  __framer__loopTransition: transition2,
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 1,
                },
              },
              baseVariant,
              gestureVariant
            ),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ig5fv.framer-1rotvzg, .framer-ig5fv .framer-1rotvzg { display: block; }",
  ".framer-ig5fv.framer-rquy2o { height: 40px; overflow: visible; position: relative; width: 40px; }",
  ".framer-ig5fv .framer-1ngm8mn { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); left: 0px; position: absolute; right: 0px; top: 0px; width: calc(100% - 0px); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 40
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"IJ7G7VnMj":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameradHkmkL0W = withCSS(Component, css, "framer-ig5fv");
export default FrameradHkmkL0W;
FrameradHkmkL0W.displayName = "Icon Tooltip Home Step 2";
FrameradHkmkL0W.defaultProps = { height: 40, width: 40 };
addPropertyControls(FrameradHkmkL0W, {
  variant: {
    options: ["x1E8Vbms3", "IJ7G7VnMj"],
    optionTitles: ["Static", "Anim"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FrameradHkmkL0W,
  [{ explicitInter: true, fonts: [] }, ...TriangleFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FrameradHkmkL0W",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "40",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"IJ7G7VnMj":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "40",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./adHkmkL0W.map
