// Generated by Framer (f2c0341)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = { FFvLZ7ILG: { hover: true } };
const serializationHash = "framer-NjjQH";
const variantClassNames = { FFvLZ7ILG: "framer-v-7di19j" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, title, width, ...props }) => {
  return {
    ...props,
    IN_NQt8n6: title ?? props.IN_NQt8n6 ?? "Linkedin",
    s0JWxFmmy: link ?? props.s0JWxFmmy,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    IN_NQt8n6,
    s0JWxFmmy,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "FFvLZ7ILG",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: s0JWxFmmy,
          motionChild: true,
          nodeId: "FFvLZ7ILG",
          scopeId: "lSOdjv5fT",
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-7di19j",
              className,
              classNames
            )} framer-1r4pu5g`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "FFvLZ7ILG",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { "FFvLZ7ILG-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7R2Vpc3QgTW9uby1yZWd1bGFy",
                    "--framer-font-family": '"Geist Mono", monospace',
                    "--framer-line-height": "120%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(15, 31, 16))",
                    "--framer-text-transform": "uppercase",
                  },
                  children: "Linkedin",
                }),
              }),
              className: "framer-dlciij",
              "data-framer-name": "Linkedin",
              fonts: ["GF;Geist Mono-regular"],
              layoutDependency: layoutDependency,
              layoutId: "sDUMFCLCC",
              style: {
                "--extracted-r6o4lv": "rgb(15, 31, 16)",
                "--framer-paragraph-spacing": "0px",
                opacity: 1,
              },
              text: IN_NQt8n6,
              variants: { "FFvLZ7ILG-hover": { opacity: 0.2 } },
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-NjjQH.framer-1r4pu5g, .framer-NjjQH .framer-1r4pu5g { display: block; }",
  ".framer-NjjQH.framer-7di19j { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-NjjQH .framer-dlciij { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 19
 * @framerIntrinsicWidth 77
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"yNsY5X9Nv":{"layout":["auto","auto"]}}}
 * @framerVariables {"IN_NQt8n6":"title","s0JWxFmmy":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerlSOdjv5fT = withCSS(Component, css, "framer-NjjQH");
export default FramerlSOdjv5fT;
FramerlSOdjv5fT.displayName = "BTN_Redes_Contact";
FramerlSOdjv5fT.defaultProps = { height: 19, width: 77 };
addPropertyControls(FramerlSOdjv5fT, {
  IN_NQt8n6: {
    defaultValue: "Linkedin",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  s0JWxFmmy: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerlSOdjv5fT,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Geist Mono",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerlSOdjv5fT",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "77",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"yNsY5X9Nv":{"layout":["auto","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerVariables: '{"IN_NQt8n6":"title","s0JWxFmmy":"link"}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "19",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./lSOdjv5fT.map
