// Generated by Framer (65c0278)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 16 14" xmlns="http://www.w3.org/2000/svg"><path d="M 7.693 0.293 C 8.084 -0.098 8.717 -0.098 9.107 0.293 L 15.027 6.213 C 15.03 6.216 15.032 6.219 15.035 6.222 C 15.098 6.286 15.152 6.358 15.195 6.437 C 15.199 6.445 15.204 6.451 15.208 6.459 C 15.231 6.503 15.249 6.55 15.266 6.599 C 15.27 6.613 15.276 6.626 15.28 6.64 C 15.306 6.729 15.32 6.823 15.32 6.92 C 15.32 6.985 15.314 7.049 15.302 7.111 C 15.295 7.147 15.285 7.183 15.274 7.218 C 15.257 7.274 15.235 7.328 15.208 7.38 C 15.205 7.385 15.202 7.391 15.199 7.396 C 15.155 7.478 15.099 7.551 15.035 7.617 C 15.032 7.62 15.03 7.624 15.027 7.627 L 9.107 13.547 C 8.717 13.937 8.084 13.937 7.693 13.547 C 7.303 13.156 7.303 12.523 7.693 12.133 L 11.906 7.92 L 1 7.92 C 0.448 7.92 0 7.472 0 6.92 C 0 6.368 0.448 5.92 1 5.92 L 11.906 5.92 L 7.693 1.707 C 7.303 1.316 7.303 0.683 7.693 0.293 Z" fill="var(--abql67, rgb(198,241,157))" height="13.839637501200533px" id="JFzNTORJv" width="15.320299999999989px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ color, fill, fillLime, height, id, width, ...props }) => {
  return {
    ...props,
    iqERCEVbm: color ?? props.iqERCEVbm ?? "rgb(15, 15, 15)",
    rC3hxLB2_: fillLime ?? props.rC3hxLB2_ ?? "rgb(198, 241, 157)",
    WjsfeBMqU: fill ?? props.WjsfeBMqU ?? "rgb(15, 31, 16)",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    WjsfeBMqU,
    iqERCEVbm,
    rC3hxLB2_,
    ...restProps
  } = getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-sbvqR", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--abql67": rC3hxLB2_, ...style },
  });
});
const css = [
  `.framer-sbvqR { -webkit-mask: ${mask}; aspect-ratio: 1.1428571428571428; background-color: var(--abql67); mask: ${mask}; width: 16px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 16
 * @framerIntrinsicHeight 14
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"WjsfeBMqU":"fill","iqERCEVbm":"color","rC3hxLB2_":"fillLime"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Vector","color":{"type":"variable","value":"abql67"},"set":{"localId":"vectorSet/uB7Vr5yRV","id":"uB7Vr5yRV","moduleId":"5ETdsmPWIAGh0xcfE0fw"}}
 */ const Icon = withCSS(Component, css, "framer-sbvqR");
Icon.displayName = "Vector";
export default Icon;
addPropertyControls(Icon, {
  WjsfeBMqU: {
    defaultValue: "rgb(15, 31, 16)",
    hidden: true,
    title: "Fill",
    type: ControlType.Color,
  },
  iqERCEVbm: {
    defaultValue: "rgb(15, 15, 15)",
    hidden: true,
    title: "Color",
    type: ControlType.Color,
  },
  rC3hxLB2_: {
    defaultValue: "rgb(198, 241, 157)",
    hidden: false,
    title: "Fill Lime",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"Vector","color":{"type":"variable","value":"abql67"},"set":{"localId":"vectorSet/uB7Vr5yRV","id":"uB7Vr5yRV","moduleId":"5ETdsmPWIAGh0xcfE0fw"}}',
        framerIntrinsicWidth: "16",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerVariables:
          '{"WjsfeBMqU":"fill","iqERCEVbm":"color","rC3hxLB2_":"fillLime"}',
        framerIntrinsicHeight: "14",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
