// Generated by Framer (7587b09)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const serializationHash = "framer-7rykU";
const variantClassNames = { F68QR8ope: "framer-v-1e9fzn6" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "F68QR8ope",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1e9fzn6",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "F68QR8ope",
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-1av9ya",
            layoutDependency: layoutDependency,
            layoutId: "FptT7sGO7",
            children: /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "fill",
                intrinsicHeight: 264,
                intrinsicWidth: 327,
                loading: getLoadingLazyAtYPosition(
                  (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 200) - 0 - 200) / 2) +
                    99.5
                ),
                pixelHeight: 528,
                pixelWidth: 654,
                sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                src: "https://framerusercontent.com/images/s8QQXBOakBHqtTR895qR17ZlJ10.png?width=654&height=528",
                srcSet:
                  "https://framerusercontent.com/images/s8QQXBOakBHqtTR895qR17ZlJ10.png?scale-down-to=512&width=654&height=528 512w,https://framerusercontent.com/images/s8QQXBOakBHqtTR895qR17ZlJ10.png?width=654&height=528 654w",
              },
              className: "framer-10h1ixo",
              "data-framer-name": "Roca medio",
              layoutDependency: layoutDependency,
              layoutId: "WzEqEI63Q",
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-7rykU.framer-10uluza, .framer-7rykU .framer-10uluza { display: block; }",
  ".framer-7rykU.framer-1e9fzn6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 200px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 200px; }",
  ".framer-7rykU .framer-1av9ya { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 200px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-7rykU .framer-10h1ixo { aspect-ratio: 1.2386363636363635 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 161px); overflow: visible; position: relative; width: 1px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerRbffTpLx0 = withCSS(Component, css, "framer-7rykU");
export default FramerRbffTpLx0;
FramerRbffTpLx0.displayName = "Rock 1";
FramerRbffTpLx0.defaultProps = { height: 200, width: 200 };
addFonts(FramerRbffTpLx0, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerRbffTpLx0",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "200",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "200",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./RbffTpLx0.map
