// Generated by Framer (a1faaee)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image as Image1,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["jSheKXCwy", "QC9DNTAsm"];
const serializationHash = "framer-4erum";
const variantClassNames = {
  jSheKXCwy: "framer-v-1iazcin",
  QC9DNTAsm: "framer-v-r0zsan",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.8,
  ease: [0.76, 0, 0.36, 1],
  type: "tween",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { loaded: "QC9DNTAsm", loading: "jSheKXCwy" };
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "jSheKXCwy",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "jSheKXCwy",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1iazcin",
            className,
            classNames
          ),
          "data-framer-name": "loading",
          layoutDependency: layoutDependency,
          layoutId: "jSheKXCwy",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { QC9DNTAsm: { "data-framer-name": "loaded" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1qiz1am",
              "data-framer-name": "Preloader",
              layoutDependency: layoutDependency,
              layoutId: "VTCbOop1I",
              style: {
                backgroundColor:
                  "var(--token-95995eb5-c56a-4901-8fd5-d6ed3e73179d, rgb(15, 15, 15))",
                opacity: 1,
              },
              variants: { QC9DNTAsm: { opacity: 0 } },
              children: /*#__PURE__*/ _jsx(Image1, {
                background: {
                  alt: "Prakriti's icon ",
                  fit: "fill",
                  intrinsicHeight: 122,
                  intrinsicWidth: 120,
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 0 + 0 + 487
                  ),
                  pixelHeight: 122,
                  pixelWidth: 120,
                  sizes: "25.5px",
                  src: "https://framerusercontent.com/images/LL5vrT8HpdhLYFBV0oFpTouJDe4.gif?width=120&height=122",
                },
                className: "framer-17rkel6",
                "data-framer-name": "OP-02",
                layoutDependency: layoutDependency,
                layoutId: "G1FZSj_Dd",
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1rtn722",
              "data-framer-name": "Preloader",
              layoutDependency: layoutDependency,
              layoutId: "I851R1myK",
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-4erum.framer-11de9tn, .framer-4erum .framer-11de9tn { display: block; }",
  ".framer-4erum.framer-1iazcin { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 800px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1440px; }",
  ".framer-4erum .framer-1qiz1am, .framer-4erum .framer-1rtn722 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: calc(var(--framer-viewport-height, 100vh) * 1); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; z-index: 9; }",
  ".framer-4erum .framer-17rkel6 { aspect-ratio: 0.9807692307692307 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 26px); overflow: visible; position: relative; width: 26px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 800
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"QC9DNTAsm":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramercCCEvFYZP = withCSS(Component, css, "framer-4erum");
export default FramercCCEvFYZP;
FramercCCEvFYZP.displayName = "preloader";
FramercCCEvFYZP.defaultProps = { height: 800, width: 1440 };
addPropertyControls(FramercCCEvFYZP, {
  variant: {
    options: ["jSheKXCwy", "QC9DNTAsm"],
    optionTitles: ["loading", "loaded"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramercCCEvFYZP, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramercCCEvFYZP",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"QC9DNTAsm":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicHeight: "800",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "1440",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./cCCEvFYZP.map
